{
  "hash": "6912fea30a9db0b283809b66caf0398b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home Exercise 2\"\nsubtitle: \"Prototyping Modules for Visual Analytics Shiny Application\"\nauthor: \"Nazia Faruqui\"\ndate: 2026-03-09\ndate-modified: \"last-modified\"\nexecute: \n  eval: true\n  echo: true\n  warning: false\n  freeze: true\n---\n\n# The Task\n\nIn this take-home exercise, we are required to select one of the modules of our proposed Shiny application and complete the following tasks:\n\n-   To evaluate and determine whether the necessary R packages needed for our Shiny application are supported in **R CRAN**,\n\n-   To prepare and test the specific R codes can be run and return the correct visual output as expected,\n\n-   To determine the parameters and outputs that will be exposed on the Shiny applications, and\n\n-   To select the appropriate Shiny UI components for exposing the parameters determined above.\n\n# 1. Getting Started\n\nFor this project, we will be looking at analysing and visualising the customer and transactions data of a Colombian Fintech company. I will be looking at the exploratory and confirmatory data analysis for the dataset.\n\n# 2. Installing and Loading R Packages\n\nThe packages used for testing as part of this exercise include the below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(tidyverse, ggstatsplot, plotly, ggiraph, ggdist, ggpubr, ggridges, ggmosaic, tidytext, wordcloud)\n```\n:::\n\n\nTwo interactive visualisation packages were evaluated: **ggiraph** and **plotly**. The ggiraph package enables interactive elements such as tooltips while preserving the ggplot2 syntax, making it suitable for Shiny applications requiring custom hover information. The plotly package was also tested because it can convert ggplot objects into fully interactive visualisations with built-in zooming, panning, and hover functionality. Both packages successfully produced interactive visualisations; however, ggiraph offers greater control over tooltip formatting while plotly provides additional interactive features such as zooming and dynamic highlighting. **Therefore, both packages will be used in the project**. ggiraph will be applied in situations where customised tooltip content is required, while plotly will be used when its default interactive behaviour and simpler implementation are sufficient.\n\nTwo packages were evaluated for statistical visualisation: **ggstatsplot** and **ggpubr**. While ggpubr provides functions for adding statistical test results to ggplot visualisations, ggstatsplot integrates visualisation, hypothesis testing, effect sizes, and confidence intervals within a single function. Due to this comprehensive functionality and ease of implementation, ggstatsplot was selected as the primary package for confirmatory data analysis.\n\n### Evaluation of packages\n\n| Package | Reason for selection |\n|--------------------|----------------------------------------------------|\n| tidyverse | Selected as the core package for data manipulation, cleaning, and visualisation (dplyr, ggplot2, tidyr) |\n| ggstatsplot | Selected because it automatically integrates statistical tests, effect sizes, and confidence intervals into visualisations, reducing the need for separate statistical coding. |\n| plotly | Selected because it automatically integrates statistical tests, effect sizes, and confidence intervals into visualisations, reducing the need for separate statistical coding. |\n| ggiraph | Selected for adding interactive visualisations with minimal code and built-in tooltips that display values when users hover over the plot. |\n| ggdist | Selected for advanced distribution visualisations such as raincloud plots and half-eye plots. |\n| ggridges | Selected for visualising ridge plots to visualise distributions across multiple groups |\n| ggmosaic | Selected for visualising mosaic plots for categorical vs categorical relationships |\n| tidytext | Selected for text analysis |\n| wordcloud | Wordcloud was used to visualise the text analysis in the form of a wordcloud, however due both text related variables having only few unique values, it did not present a good visual, hence not selected. |\n\n# 3. The Data\n\nWe will be looking at the [**COFINFAD: Colombian Fintech Financial Analytics Dataset**](https://data.mendeley.com/datasets/mhb4zn3258/1) for this project. There are two csv files as part of this dataset - *customer_data.csv* and *transactions_data.csv.* The datasets are linked using the customer_id field. ***read_csv()*** function of **readr** package will be used to import the data into R.\n\nThe transaction dataset will likely not be used in this project because the relevant transaction information has already been aggregated in the customer dataset. The customer dataset includes key summary variables such as the total number of transactions, average transaction value, total transaction volume, and the dates of the first and last transactions for each customer. Since these measures capture the overall transaction behaviour at the customer level, most of the required analyses can be conducted using this dataset alone.\n\nThe transaction dataset mainly provides additional details such as the exact date of each individual transaction and the type of transaction (for example, payment, transfer, withdrawal, or deposit). However, this information does not appear to add significant value to the objectives of the current analysis, which focus on customer-level patterns rather than detailed transaction timelines.\n\nTherefore, the customer dataset will serve as the primary dataset for this project, while the transaction dataset is unlikely to be used unless more detailed transaction-level analysis becomes necessary.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- read_csv(\"../data/customer_data.csv\")\n```\n:::\n\n\nUpon importing, we need to first check whether the imported data is accurate and complete. To do that, we can go to the Environment tab in RStudio -\\> click on df under Data, where we can see that there are 48723 rows and 54 columns, which is the same as the original excel file.\n\nAdditionally, the `str()` function can also be used to check the above. It also gives us the data types of the variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nspc_tbl_ [48,723 × 54] (S3: spec_tbl_df/tbl_df/tbl/data.frame)\n $ customer_id               : num [1:48723] 93716481 49020929 52690950 23199751 61997066 ...\n $ age                       : num [1:48723] 44 44 45 45 44 45 44 44 45 44 ...\n $ gender                    : chr [1:48723] \"Male\" \"Male\" \"Male\" \"Male\" ...\n $ location                  : chr [1:48723] \"Pereira, Risaralda\" \"Cali, Valle del Cauca\" \"Barranquilla, Atlántico\" \"Bogotá, Cundinamarca\" ...\n $ income_bracket            : chr [1:48723] \"Very High\" \"Medium\" \"High\" \"High\" ...\n $ occupation                : chr [1:48723] \"Engineer\" \"Construction Worker\" \"Construction Worker\" \"Electrician\" ...\n $ education_level           : chr [1:48723] \"Master\" \"Bachelor\" \"Bachelor\" \"High School\" ...\n $ marital_status            : chr [1:48723] \"Married\" \"Married\" \"Married\" \"Single\" ...\n $ household_size            : num [1:48723] 5 2 4 2 3 4 4 3 1 3 ...\n $ acquisition_channel       : chr [1:48723] \"Partnership\" \"Paid Ad\" \"Paid Ad\" \"Referral\" ...\n $ customer_segment          : chr [1:48723] \"occasional\" \"regular\" \"inactive\" \"inactive\" ...\n $ savings_account           : logi [1:48723] TRUE TRUE TRUE TRUE TRUE TRUE ...\n $ credit_card               : logi [1:48723] TRUE FALSE FALSE FALSE TRUE TRUE ...\n $ personal_loan             : logi [1:48723] FALSE FALSE FALSE FALSE FALSE FALSE ...\n $ investment_account        : logi [1:48723] FALSE FALSE TRUE TRUE FALSE TRUE ...\n $ insurance_product         : logi [1:48723] TRUE FALSE TRUE FALSE FALSE FALSE ...\n $ active_products           : num [1:48723] 1 5 3 2 1 1 1 4 2 3 ...\n $ app_logins_frequency      : num [1:48723] 15 30 4 15 19 15 44 22 7 11 ...\n $ feature_usage_diversity   : num [1:48723] 3 0 4 4 1 4 6 1 1 6 ...\n $ bill_payment_user         : logi [1:48723] FALSE TRUE TRUE TRUE FALSE TRUE ...\n $ auto_savings_enabled      : logi [1:48723] FALSE FALSE FALSE FALSE FALSE TRUE ...\n $ credit_utilization_ratio  : num [1:48723] 0.179 NA NA NA 0.404 ...\n $ international_transactions: num [1:48723] 1 1 1 1 0 0 0 0 0 1 ...\n $ failed_transactions       : num [1:48723] 0 0 0 1 0 0 1 1 0 0 ...\n $ tx_count                  : num [1:48723] 76 10 10 23 18 15 24 45 134 13 ...\n $ avg_tx_value              : num [1:48723] 1679872 5445810 640335 660180 14574469 ...\n $ total_tx_volume           : num [1:48723] 1.28e+08 5.45e+07 6.40e+06 1.52e+07 2.62e+08 ...\n $ first_tx                  : Date[1:48723], format: \"2023-01-05\" \"2023-02-05\" ...\n $ last_tx                   : Date[1:48723], format: \"2023-12-25\" \"2023-12-20\" ...\n $ base_satisfaction         : num [1:48723] 9.21 6.07 8.2 7.53 6.61 ...\n $ tx_satisfaction           : num [1:48723] 0.38 0.05 0.05 0.115 0.09 0.075 0.12 0.225 0.67 0.065 ...\n $ product_satisfaction      : num [1:48723] 0.6 0.2 0.6 0.4 0.4 0.6 0.4 0.4 0.6 0.8 ...\n $ satisfaction_score        : num [1:48723] 5 3 4 4 3 4 4 4 5 4 ...\n $ nps_score                 : num [1:48723] -7 -46 -29 -31 -47 -29 -34 -36 -4 -27 ...\n $ last_survey_date          : Date[1:48723], format: \"2023-12-16\" \"2023-05-05\" ...\n $ support_tickets_count     : num [1:48723] 1 1 0 2 2 1 1 0 2 0 ...\n $ resolved_tickets_ratio    : num [1:48723] 0 1 0 0.5 1 1 1 0 1 0 ...\n $ app_store_rating          : num [1:48723] 3.5 4 5 4.5 4 4 5 4.5 4.5 4.5 ...\n $ feedback_sentiment        : chr [1:48723] \"Neutral\" \"Positive\" \"Positive\" \"Positive\" ...\n $ feature_requests          : chr [1:48723] \"Budgeting tools\" NA NA \"Cryptocurrency trading, Budgeting tools\" ...\n $ complaint_topics          : chr [1:48723] NA NA NA NA ...\n $ clv_segment               : chr [1:48723] \"Gold\" \"Bronze\" \"Gold\" \"Bronze\" ...\n $ monthly_transaction_count : num [1:48723] 1.43 1.57 2.5 1.56 2.11 ...\n $ average_transaction_value : num [1:48723] 6054025 2127414 3575915 1513354 612674 ...\n $ total_transaction_volume  : num [1:48723] 60540250 23401550 35759150 21186950 11640800 ...\n $ transaction_frequency     : num [1:48723] 0.0308 0.0329 0.05 0.0478 0.0619 ...\n $ last_transaction_date     : Date[1:48723], format: \"2023-12-05\" \"2023-12-18\" ...\n $ preferred_transaction_type: chr [1:48723] \"Transfer\" \"Transfer\" \"Transfer\" \"Transfer\" ...\n $ first_transaction_date    : Date[1:48723], format: \"2023-01-05\" \"2023-02-05\" ...\n $ weekend_transaction_ratio : num [1:48723] 0.3 0.182 0.3 0.143 0.316 ...\n $ avg_daily_transactions    : num [1:48723] 0.0308 0.0329 0.05 0.0478 0.0619 ...\n $ customer_tenure           : num [1:48723] 11.63 11.5 8.77 10.73 11.63 ...\n $ churn_probability         : num [1:48723] 0.362 0.182 0.321 0.337 0.398 ...\n $ customer_lifetime_value   : num [1:48723] 3.12e+08 1.67e+08 1.94e+07 3.60e+07 3.05e+08 ...\n - attr(*, \"spec\")=\n  .. cols(\n  ..   customer_id = col_double(),\n  ..   age = col_double(),\n  ..   gender = col_character(),\n  ..   location = col_character(),\n  ..   income_bracket = col_character(),\n  ..   occupation = col_character(),\n  ..   education_level = col_character(),\n  ..   marital_status = col_character(),\n  ..   household_size = col_double(),\n  ..   acquisition_channel = col_character(),\n  ..   customer_segment = col_character(),\n  ..   savings_account = col_logical(),\n  ..   credit_card = col_logical(),\n  ..   personal_loan = col_logical(),\n  ..   investment_account = col_logical(),\n  ..   insurance_product = col_logical(),\n  ..   active_products = col_double(),\n  ..   app_logins_frequency = col_double(),\n  ..   feature_usage_diversity = col_double(),\n  ..   bill_payment_user = col_logical(),\n  ..   auto_savings_enabled = col_logical(),\n  ..   credit_utilization_ratio = col_double(),\n  ..   international_transactions = col_double(),\n  ..   failed_transactions = col_double(),\n  ..   tx_count = col_double(),\n  ..   avg_tx_value = col_double(),\n  ..   total_tx_volume = col_double(),\n  ..   first_tx = col_date(format = \"\"),\n  ..   last_tx = col_date(format = \"\"),\n  ..   base_satisfaction = col_double(),\n  ..   tx_satisfaction = col_double(),\n  ..   product_satisfaction = col_double(),\n  ..   satisfaction_score = col_double(),\n  ..   nps_score = col_double(),\n  ..   last_survey_date = col_date(format = \"\"),\n  ..   support_tickets_count = col_double(),\n  ..   resolved_tickets_ratio = col_double(),\n  ..   app_store_rating = col_double(),\n  ..   feedback_sentiment = col_character(),\n  ..   feature_requests = col_character(),\n  ..   complaint_topics = col_character(),\n  ..   clv_segment = col_character(),\n  ..   monthly_transaction_count = col_double(),\n  ..   average_transaction_value = col_double(),\n  ..   total_transaction_volume = col_double(),\n  ..   transaction_frequency = col_double(),\n  ..   last_transaction_date = col_date(format = \"\"),\n  ..   preferred_transaction_type = col_character(),\n  ..   first_transaction_date = col_date(format = \"\"),\n  ..   weekend_transaction_ratio = col_double(),\n  ..   avg_daily_transactions = col_double(),\n  ..   customer_tenure = col_double(),\n  ..   churn_probability = col_double(),\n  ..   customer_lifetime_value = col_double()\n  .. )\n - attr(*, \"problems\")=<externalptr> \n```\n\n\n:::\n:::\n\n\nEach row in the dataset represents an individual customer, while each columns describes different aspects of the customer’s profile and behaviour. The variables provide information across several key areas, including **demographic characteristics** (such as age, gender, location, income bracket, education level, and marital status), **financial product ownership** (for example savings accounts, credit cards, loans, investment accounts, and insurance products), and **digital engagement** (such as app login frequency and feature usage).\n\nIn addition, the dataset includes **transaction-related metrics**, such as the number of transactions, average transaction value, total transaction volume, transaction frequency, and the dates of the first and last transactions. The dataset also captures **customer experience and satisfaction indicators**, including satisfaction scores, Net Promoter Score (NPS), app store ratings, and feedback sentiment. Finally, it provides **customer lifecycle and support information**, such as support tickets, complaint topics, customer tenure, churn probability, and estimated customer lifetime value. Together, these variables offer a comprehensive view of customer behaviour, engagement, and value.\n\nWe also use `summary()` to examine the distribution of each variable and verify that the values fall within reasonable and expected ranges. This helps identify potential data quality issues such as invalid values, extreme outliers, or missing data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  customer_id            age           gender            location        \n Min.   :10000617   Min.   :29.00   Length:48723       Length:48723      \n 1st Qu.:32708346   1st Qu.:30.00   Class :character   Class :character  \n Median :55174470   Median :45.00   Mode  :character   Mode  :character  \n Mean   :55027986   Mean   :44.54                                        \n 3rd Qu.:77242332   3rd Qu.:59.00                                        \n Max.   :99999798   Max.   :60.00                                        \n                                                                         \n income_bracket      occupation        education_level    marital_status    \n Length:48723       Length:48723       Length:48723       Length:48723      \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n household_size   acquisition_channel customer_segment   savings_account\n Min.   : 1.000   Length:48723        Length:48723       Mode :logical  \n 1st Qu.: 2.000   Class :character    Class :character   FALSE:10264    \n Median : 3.000   Mode  :character    Mode  :character   TRUE :38459    \n Mean   : 3.496                                                         \n 3rd Qu.: 4.000                                                         \n Max.   :13.000                                                         \n                                                                        \n credit_card     personal_loan   investment_account insurance_product\n Mode :logical   Mode :logical   Mode :logical      Mode :logical    \n FALSE:18263     FALSE:33321     FALSE:27985        FALSE:38388      \n TRUE :30460     TRUE :15402     TRUE :20738        TRUE :10335      \n                                                                     \n                                                                     \n                                                                     \n                                                                     \n active_products app_logins_frequency feature_usage_diversity bill_payment_user\n Min.   :1.000   Min.   :  4.00       Min.   : 0.00           Mode :logical    \n 1st Qu.:1.000   1st Qu.: 15.00       1st Qu.: 1.00           FALSE:14553      \n Median :2.000   Median : 22.00       Median : 2.00           TRUE :34170      \n Mean   :2.095   Mean   : 22.38       Mean   : 2.37                            \n 3rd Qu.:3.000   3rd Qu.: 30.00       3rd Qu.: 4.00                            \n Max.   :5.000   Max.   :100.00       Max.   :10.00                            \n                                                                               \n auto_savings_enabled credit_utilization_ratio international_transactions\n Mode :logical        Min.   :0.0002           Min.   :0.0000            \n FALSE:29173          1st Qu.:0.1619           1st Qu.:0.0000            \n TRUE :19550          Median :0.2659           Median :0.0000            \n                      Mean   :0.2869           Mean   :0.4939            \n                      3rd Qu.:0.3910           3rd Qu.:1.0000            \n                      Max.   :0.9375           Max.   :6.0000            \n                      NA's   :18263                                      \n failed_transactions    tx_count         avg_tx_value      total_tx_volume    \n Min.   :0.0000      Min.   :   10.00   Min.   :  318215   Min.   :3.182e+06  \n 1st Qu.:0.0000      1st Qu.:   12.00   1st Qu.: 1339114   1st Qu.:2.016e+07  \n Median :0.0000      Median :   18.00   Median : 1763107   Median :4.808e+07  \n Mean   :0.1988      Mean   :   64.84   Mean   : 3564852   Mean   :2.575e+08  \n 3rd Qu.:0.0000      3rd Qu.:   35.00   3rd Qu.: 4658536   3rd Qu.:1.204e+08  \n Max.   :4.0000      Max.   :77465.00   Max.   :51670303   Max.   :1.073e+12  \n                                                                              \n    first_tx             last_tx           base_satisfaction tx_satisfaction \n Min.   :2023-01-04   Min.   :2023-05-11   Min.   : 4.250    Min.   :0.0500  \n 1st Qu.:2023-01-07   1st Qu.:2023-12-05   1st Qu.: 7.326    1st Qu.:0.0600  \n Median :2023-01-14   Median :2023-12-19   Median : 8.005    Median :0.0900  \n Mean   :2023-01-21   Mean   :2023-12-11   Mean   : 8.001    Mean   :0.1772  \n 3rd Qu.:2023-01-28   3rd Qu.:2023-12-26   3rd Qu.: 8.676    3rd Qu.:0.1750  \n Max.   :2023-08-10   Max.   :2023-12-29   Max.   :11.937    Max.   :1.0000  \n                                                                             \n product_satisfaction satisfaction_score   nps_score      last_survey_date    \n Min.   :0.0000       Min.   :2.000      Min.   :-80.00   Min.   :2023-01-01  \n 1st Qu.:0.4000       1st Qu.:4.000      1st Qu.:-34.00   1st Qu.:2023-04-01  \n Median :0.4000       Median :4.000      Median :-28.00   Median :2023-07-03  \n Mean   :0.4737       Mean   :4.162      Mean   :-26.76   Mean   :2023-07-02  \n 3rd Qu.:0.6000       3rd Qu.:5.000      3rd Qu.:-19.00   3rd Qu.:2023-10-01  \n Max.   :1.0000       Max.   :6.000      Max.   : 23.00   Max.   :2023-12-31  \n                                                                              \n support_tickets_count resolved_tickets_ratio app_store_rating\n Min.   :0.0000        Min.   :0.0000         Min.   :2.000   \n 1st Qu.:0.0000        1st Qu.:0.0000         1st Qu.:4.000   \n Median :1.0000        Median :0.5000         Median :4.000   \n Mean   :0.9975        Mean   :0.5062         Mean   :4.156   \n 3rd Qu.:2.0000        3rd Qu.:1.0000         3rd Qu.:4.500   \n Max.   :7.0000        Max.   :1.0000         Max.   :5.000   \n                                                              \n feedback_sentiment feature_requests   complaint_topics   clv_segment       \n Length:48723       Length:48723       Length:48723       Length:48723      \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n monthly_transaction_count average_transaction_value total_transaction_volume\n Min.   :   1.000          Min.   :  318215          Min.   :3.182e+06       \n 1st Qu.:   1.600          1st Qu.: 1339114          1st Qu.:2.016e+07       \n Median :   2.000          Median : 1763107          Median :4.808e+07       \n Mean   :   5.765          Mean   : 3564852          Mean   :2.575e+08       \n 3rd Qu.:   3.091          3rd Qu.: 4658536          3rd Qu.:1.204e+08       \n Max.   :6455.417          Max.   :51670303          Max.   :1.073e+12       \n                                                                             \n transaction_frequency last_transaction_date preferred_transaction_type\n Min.   :  0.02786     Min.   :2023-05-11    Length:48723              \n 1st Qu.:  0.04154     1st Qu.:2023-12-05    Class :character          \n Median :  0.05764     Median :2023-12-19    Mode  :character          \n Mean   :  0.18656     Mean   :2023-12-11                              \n 3rd Qu.:  0.10314     3rd Qu.:2023-12-26                              \n Max.   :215.77994     Max.   :2023-12-29                              \n                                                                       \n first_transaction_date weekend_transaction_ratio avg_daily_transactions\n Min.   :2023-01-04     Min.   :0.0000            Min.   :  0.02786     \n 1st Qu.:2023-01-07     1st Qu.:0.2143            1st Qu.:  0.04154     \n Median :2023-01-14     Median :0.2800            Median :  0.05764     \n Mean   :2023-01-21     Mean   :0.2829            Mean   :  0.18656     \n 3rd Qu.:2023-01-28     3rd Qu.:0.3400            3rd Qu.:  0.10314     \n Max.   :2023-08-10     Max.   :0.9091            Max.   :215.77994     \n                                                                        \n customer_tenure churn_probability customer_lifetime_value\n Min.   : 4.70   Min.   :0.1143    Min.   :0.000e+00      \n 1st Qu.:11.17   1st Qu.:0.3029    1st Qu.:5.841e+07      \n Median :11.63   Median :0.3540    Median :1.297e+08      \n Mean   :11.37   Mean   :0.3429    Mean   :3.282e+08      \n 3rd Qu.:11.87   3rd Qu.:0.3927    3rd Qu.:2.974e+08      \n Max.   :11.97   Max.   :0.5006    Max.   :1.777e+10      \n                                                          \n```\n\n\n:::\n:::\n\n\nThe summary output confirms that the values in the dataset fall within reasonable ranges for the respective variables. Demographic variables such as *age* and *household_size* show plausible minimum and maximum values, while transaction-related variables such as *tx_count*, *avg_tx_value*, and *total_tx_volume* contain positive values consistent with financial activity. Ratio-based variables, including *credit_utilization_ratio*, *resolved_tickets_ratio*, *weekend_transaction_ratio*, and *churn_probability*, fall between 0 and 1 as expected. Additionally, the summary indicates that most variables do not contain missing values, with the exception of *credit_utilization_ratio*, which contains some missing entries likely due to customers who do not hold credit cards. Overall, the results suggest that the dataset does not contain obvious invalid values and is suitable for further analysis.\n\n# 4. Data Wrangling\n\n## 4.1 Checking for missing values\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolSums(is.na(df))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               customer_id                        age \n                         0                          0 \n                    gender                   location \n                         0                          0 \n            income_bracket                 occupation \n                         0                          0 \n           education_level             marital_status \n                         0                          0 \n            household_size        acquisition_channel \n                         0                          0 \n          customer_segment            savings_account \n                         0                          0 \n               credit_card              personal_loan \n                         0                          0 \n        investment_account          insurance_product \n                         0                          0 \n           active_products       app_logins_frequency \n                         0                          0 \n   feature_usage_diversity          bill_payment_user \n                         0                          0 \n      auto_savings_enabled   credit_utilization_ratio \n                         0                      18263 \ninternational_transactions        failed_transactions \n                         0                          0 \n                  tx_count               avg_tx_value \n                         0                          0 \n           total_tx_volume                   first_tx \n                         0                          0 \n                   last_tx          base_satisfaction \n                         0                          0 \n           tx_satisfaction       product_satisfaction \n                         0                          0 \n        satisfaction_score                  nps_score \n                         0                          0 \n          last_survey_date      support_tickets_count \n                         0                          0 \n    resolved_tickets_ratio           app_store_rating \n                         0                          0 \n        feedback_sentiment           feature_requests \n                         0                      16115 \n          complaint_topics                clv_segment \n                     24346                          0 \n monthly_transaction_count  average_transaction_value \n                         0                          0 \n  total_transaction_volume      transaction_frequency \n                         0                          0 \n     last_transaction_date preferred_transaction_type \n                         0                          0 \n    first_transaction_date  weekend_transaction_ratio \n                         0                          0 \n    avg_daily_transactions            customer_tenure \n                         0                          0 \n         churn_probability    customer_lifetime_value \n                         0                          0 \n```\n\n\n:::\n:::\n\n\nThree variables contain missing data. The variable credit_utilization_ratio contains 18,263 missing values, which corresponds to customers who do not hold a credit card and therefore do not have a recorded utilization ratio. Additionally, feature_requests contains 16,115 missing values and complaint_topics contains 24,346 missing values. These missing values are expected, as not all customers provide feature requests or submit complaints. Since these missing values reflect the absence of feedback rather than data errors, they will be retained in the dataset for analysis.\n\n## 4.2 Checking for duplicates\n\nTo ensure that each observation represents a unique customer, the dataset is checked for duplicate values in the customer_id variable. This is done using the duplicated() function in R to identify whether any customer IDs appear more than once. The results show that there are no duplicate *customer_id* values in the dataset, confirming that each row corresponds to a unique customer record.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(duplicated(df$customer_id))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\n## 4.3 Converting variables\n\nSome variables in the dataset are converted to more appropriate data types to ensure they are handled correctly during analysis. Several categorical variables are originally stored as character variables and are converted to factor variables so that they are treated as categorical data rather than plain text. These variables include *gender*, *income_bracket*, *occupation*, *education_level*, *marital_status*, *acquisition_channel*, *customer_segment*, *feedback_sentiment*, *clv_segment*, and *preferred_transaction_type*. Converting these variables to factors allows them to be used more effectively in grouping, summarisation, and statistical modelling.\n\nIn addition, the variable *customer_id* is converted from numeric to character format. Since this variable serves only as a unique identifier for each customer and is not used in numerical calculations, converting it to a character variable prevents it from being mistakenly treated as a quantitative variable during analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf$customer_id <- as.character(df$customer_id)\n\ndf$gender <- as.factor(df$gender)\ndf$income_bracket <- as.factor(df$income_bracket)\ndf$occupation <- as.factor(df$occupation)\ndf$education_level <- as.factor(df$education_level)\ndf$marital_status <- as.factor(df$marital_status)\ndf$acquisition_channel <- as.factor(df$acquisition_channel)\ndf$customer_segment <- as.factor(df$customer_segment)\ndf$feedback_sentiment <- as.factor(df$feedback_sentiment)\ndf$clv_segment <- as.factor(df$clv_segment)\ndf$preferred_transaction_type <- as.factor(df$preferred_transaction_type)\ndf$location <- as.factor(df$location)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nspc_tbl_ [48,723 × 54] (S3: spec_tbl_df/tbl_df/tbl/data.frame)\n $ customer_id               : chr [1:48723] \"93716481\" \"49020929\" \"52690950\" \"23199751\" ...\n $ age                       : num [1:48723] 44 44 45 45 44 45 44 44 45 44 ...\n $ gender                    : Factor w/ 3 levels \"Female\",\"Male\",..: 2 2 2 2 1 1 2 2 2 2 ...\n $ location                  : Factor w/ 18 levels \"Armenia, Quindío\",..: 14 5 2 3 3 3 3 3 6 3 ...\n $ income_bracket            : Factor w/ 4 levels \"High\",\"Low\",\"Medium\",..: 4 3 1 1 3 3 3 3 3 3 ...\n $ occupation                : Factor w/ 35 levels \"Accountant\",\"Architect\",..: 14 8 8 13 7 2 7 3 16 19 ...\n $ education_level           : Factor w/ 4 levels \"Bachelor\",\"High School\",..: 3 1 1 2 1 4 3 1 3 1 ...\n $ marital_status            : Factor w/ 4 levels \"Divorced\",\"Married\",..: 2 2 2 3 2 2 3 2 3 3 ...\n $ household_size            : num [1:48723] 5 2 4 2 3 4 4 3 1 3 ...\n $ acquisition_channel       : Factor w/ 4 levels \"Organic\",\"Paid Ad\",..: 3 2 2 4 2 4 1 4 1 2 ...\n $ customer_segment          : Factor w/ 4 levels \"inactive\",\"occasional\",..: 2 4 1 1 3 1 1 4 1 3 ...\n $ savings_account           : logi [1:48723] TRUE TRUE TRUE TRUE TRUE TRUE ...\n $ credit_card               : logi [1:48723] TRUE FALSE FALSE FALSE TRUE TRUE ...\n $ personal_loan             : logi [1:48723] FALSE FALSE FALSE FALSE FALSE FALSE ...\n $ investment_account        : logi [1:48723] FALSE FALSE TRUE TRUE FALSE TRUE ...\n $ insurance_product         : logi [1:48723] TRUE FALSE TRUE FALSE FALSE FALSE ...\n $ active_products           : num [1:48723] 1 5 3 2 1 1 1 4 2 3 ...\n $ app_logins_frequency      : num [1:48723] 15 30 4 15 19 15 44 22 7 11 ...\n $ feature_usage_diversity   : num [1:48723] 3 0 4 4 1 4 6 1 1 6 ...\n $ bill_payment_user         : logi [1:48723] FALSE TRUE TRUE TRUE FALSE TRUE ...\n $ auto_savings_enabled      : logi [1:48723] FALSE FALSE FALSE FALSE FALSE TRUE ...\n $ credit_utilization_ratio  : num [1:48723] 0.179 NA NA NA 0.404 ...\n $ international_transactions: num [1:48723] 1 1 1 1 0 0 0 0 0 1 ...\n $ failed_transactions       : num [1:48723] 0 0 0 1 0 0 1 1 0 0 ...\n $ tx_count                  : num [1:48723] 76 10 10 23 18 15 24 45 134 13 ...\n $ avg_tx_value              : num [1:48723] 1679872 5445810 640335 660180 14574469 ...\n $ total_tx_volume           : num [1:48723] 1.28e+08 5.45e+07 6.40e+06 1.52e+07 2.62e+08 ...\n $ first_tx                  : Date[1:48723], format: \"2023-01-05\" \"2023-02-05\" ...\n $ last_tx                   : Date[1:48723], format: \"2023-12-25\" \"2023-12-20\" ...\n $ base_satisfaction         : num [1:48723] 9.21 6.07 8.2 7.53 6.61 ...\n $ tx_satisfaction           : num [1:48723] 0.38 0.05 0.05 0.115 0.09 0.075 0.12 0.225 0.67 0.065 ...\n $ product_satisfaction      : num [1:48723] 0.6 0.2 0.6 0.4 0.4 0.6 0.4 0.4 0.6 0.8 ...\n $ satisfaction_score        : num [1:48723] 5 3 4 4 3 4 4 4 5 4 ...\n $ nps_score                 : num [1:48723] -7 -46 -29 -31 -47 -29 -34 -36 -4 -27 ...\n $ last_survey_date          : Date[1:48723], format: \"2023-12-16\" \"2023-05-05\" ...\n $ support_tickets_count     : num [1:48723] 1 1 0 2 2 1 1 0 2 0 ...\n $ resolved_tickets_ratio    : num [1:48723] 0 1 0 0.5 1 1 1 0 1 0 ...\n $ app_store_rating          : num [1:48723] 3.5 4 5 4.5 4 4 5 4.5 4.5 4.5 ...\n $ feedback_sentiment        : Factor w/ 3 levels \"Negative\",\"Neutral\",..: 2 3 3 3 3 3 3 3 3 3 ...\n $ feature_requests          : chr [1:48723] \"Budgeting tools\" NA NA \"Cryptocurrency trading, Budgeting tools\" ...\n $ complaint_topics          : chr [1:48723] NA NA NA NA ...\n $ clv_segment               : Factor w/ 4 levels \"Bronze\",\"Gold\",..: 2 1 2 1 2 1 1 3 3 3 ...\n $ monthly_transaction_count : num [1:48723] 1.43 1.57 2.5 1.56 2.11 ...\n $ average_transaction_value : num [1:48723] 6054025 2127414 3575915 1513354 612674 ...\n $ total_transaction_volume  : num [1:48723] 60540250 23401550 35759150 21186950 11640800 ...\n $ transaction_frequency     : num [1:48723] 0.0308 0.0329 0.05 0.0478 0.0619 ...\n $ last_transaction_date     : Date[1:48723], format: \"2023-12-05\" \"2023-12-18\" ...\n $ preferred_transaction_type: Factor w/ 4 levels \"Deposit\",\"Payment\",..: 3 3 3 3 2 3 2 3 3 3 ...\n $ first_transaction_date    : Date[1:48723], format: \"2023-01-05\" \"2023-02-05\" ...\n $ weekend_transaction_ratio : num [1:48723] 0.3 0.182 0.3 0.143 0.316 ...\n $ avg_daily_transactions    : num [1:48723] 0.0308 0.0329 0.05 0.0478 0.0619 ...\n $ customer_tenure           : num [1:48723] 11.63 11.5 8.77 10.73 11.63 ...\n $ churn_probability         : num [1:48723] 0.362 0.182 0.321 0.337 0.398 ...\n $ customer_lifetime_value   : num [1:48723] 3.12e+08 1.67e+08 1.94e+07 3.60e+07 3.05e+08 ...\n - attr(*, \"spec\")=\n  .. cols(\n  ..   customer_id = col_double(),\n  ..   age = col_double(),\n  ..   gender = col_character(),\n  ..   location = col_character(),\n  ..   income_bracket = col_character(),\n  ..   occupation = col_character(),\n  ..   education_level = col_character(),\n  ..   marital_status = col_character(),\n  ..   household_size = col_double(),\n  ..   acquisition_channel = col_character(),\n  ..   customer_segment = col_character(),\n  ..   savings_account = col_logical(),\n  ..   credit_card = col_logical(),\n  ..   personal_loan = col_logical(),\n  ..   investment_account = col_logical(),\n  ..   insurance_product = col_logical(),\n  ..   active_products = col_double(),\n  ..   app_logins_frequency = col_double(),\n  ..   feature_usage_diversity = col_double(),\n  ..   bill_payment_user = col_logical(),\n  ..   auto_savings_enabled = col_logical(),\n  ..   credit_utilization_ratio = col_double(),\n  ..   international_transactions = col_double(),\n  ..   failed_transactions = col_double(),\n  ..   tx_count = col_double(),\n  ..   avg_tx_value = col_double(),\n  ..   total_tx_volume = col_double(),\n  ..   first_tx = col_date(format = \"\"),\n  ..   last_tx = col_date(format = \"\"),\n  ..   base_satisfaction = col_double(),\n  ..   tx_satisfaction = col_double(),\n  ..   product_satisfaction = col_double(),\n  ..   satisfaction_score = col_double(),\n  ..   nps_score = col_double(),\n  ..   last_survey_date = col_date(format = \"\"),\n  ..   support_tickets_count = col_double(),\n  ..   resolved_tickets_ratio = col_double(),\n  ..   app_store_rating = col_double(),\n  ..   feedback_sentiment = col_character(),\n  ..   feature_requests = col_character(),\n  ..   complaint_topics = col_character(),\n  ..   clv_segment = col_character(),\n  ..   monthly_transaction_count = col_double(),\n  ..   average_transaction_value = col_double(),\n  ..   total_transaction_volume = col_double(),\n  ..   transaction_frequency = col_double(),\n  ..   last_transaction_date = col_date(format = \"\"),\n  ..   preferred_transaction_type = col_character(),\n  ..   first_transaction_date = col_date(format = \"\"),\n  ..   weekend_transaction_ratio = col_double(),\n  ..   avg_daily_transactions = col_double(),\n  ..   customer_tenure = col_double(),\n  ..   churn_probability = col_double(),\n  ..   customer_lifetime_value = col_double()\n  .. )\n - attr(*, \"problems\")=<externalptr> \n```\n\n\n:::\n:::\n\n\n::: callout-note\nThe dataset contains two sets of transaction metrics. The variables *avg_tx_value*, *total_tx_volume, first_tx, last_tx* represent aggregated transaction behaviour derived from the transaction dataset. A second set of transaction-related variables (average_transaction_value, total_transaction_volume, first_transaction_date, last_transaction_date) appears to represent derived behavioural metrics and will not be used in the analysis to avoid duplication. Additionally, transaction_frequency and avg_daily_transactions both calculate the average number of transactions per day, hence only avg_daily_transactions will be used for analysis.\n:::\n\n# 5. Univariate Analysis\n\nFor analyses involving a single variable, only **exploratory data analysis (EDA)** will be conducted. Univariate analysis focuses on understanding the distribution and characteristics of individual variables using visualisations such as histograms, density plots, and boxplots. Since there are no predefined reference values for these variables, confirmatory analysis is not applicable.\n\n### Demographics\n\nThis section will examine the distribution of demographic variables that describe the characteristics of the customer base. The variables include *age*, *gender*, *location*, *income_bracket*, *education_level*, *marital_status*, *occupation*, and *household_size*.\n\nPossible plots:\n\nbar chart (all variables),\n\nhistogram and boxplot (age, household_size)\n\n### Transaction behaviour\n\nThis section explores variables related to customer financial activity. Key variables include *tx_count*, *avg_tx_value*, *total_tx_volume, preferred_transaction_type, avg_daily_transactions,* and *weekend_transaction_ratio.*\n\nPossible plots:\n\nhistogram and density plot (avg_tx_value, total_tx_volume, avg_daily_transactions, weekend transaction ratio, tx_count),\n\nbar chart (preferred_transaction_type),\n\nboxplot (all variables except preferred_transaction_type)\n\n### Product ownership\n\nThis section analyses the distribution of financial products held by customers. Relevant variables include *savings_account*, *credit_card*, *personal_loan*, *investment_account*, *insurance_product*, and *active_products*.\n\nPossible plot: bar chart\n\n### App Usage and Engagement\n\nThis section examines variables related to customer interaction with the digital platform. These include *app_logins_frequency*, *feature_usage_diversity*, *bill_payment_user*, *auto_savings_enabled*.\n\nPossible plot: bar chart\n\n### Customer Satisfaction\n\nThis section explores customer experience indicators including *satisfaction_score*, *nps_score*, *base_satisfaction, tx_satisfaction, product_satisfaction,* *app_store_rating*, *feedback_sentiment*.\n\nPossible plots:\n\nhistogram (nps_score, base_satisfaction, tx_satisfaction, product_satisfaction, app_store_rating, satisfaction_score),\n\nbar chart (feedback_sentiment)\n\nboxplot (all variables except feedback_sentiment)\n\n### Testing the codes for the plots:\n\n1.  **Bar chart:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngender_counts <- df %>%\n  count(gender)\n\nggplot(gender_counts, aes(x = gender, #input$demo\n                          y = n)) + \n  geom_col(fill = \"lightblue\") + \n  geom_text(aes(label = n),\n            vjust = -0.3) +\n  labs(\n    x = \"Gender\", \n    y = \"Number of Customers\"\n  )\n```\n\n::: {.cell-output-display}\n![](THE02_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n2.  **Histogram (Checking interactivity using ggiraph and plotly):**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngg_hist <- ggplot(df, aes(x = avg_tx_value)) + #input$tran\n  geom_histogram_interactive(\n    aes(\n      tooltip = paste0(\n        \"Count: \", after_stat(count),\n        \"<br>Transaction Value Range: \",\n        round(after_stat(xmin), 0), \" - \",\n        round(after_stat(xmax), 0)\n      )\n    ),\n    bins = 30,\n    boundary = 0,\n    fill = \"lightblue\",\n    color = \"grey30\"\n  ) +\n  labs(\n    title = \"Distribution of Average Transaction Value\",\n    x = \"Average Transaction Value\",\n    y = \"Count\"\n  )\n\ngirafe(\n  ggobj = gg_hist,\n  width_svg = 8,\n  height_svg = 5\n)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"girafe html-widget html-fill-item\" id=\"htmlwidget-4fe956d136e1e66e36a3\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-4fe956d136e1e66e36a3\">{\"x\":{\"html\":\"<?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?>\\n<svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' class='ggiraph-svg' role='graphics-document' id='svg_07f55b258dd1de09' viewBox='0 0 576 360'>\\n <defs id='svg_07f55b258dd1de09_defs'>\\n  <clipPath id='svg_07f55b258dd1de09_c1'>\\n   <rect x='0' y='0' width='576' height='360'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_07f55b258dd1de09_c2'>\\n   <rect x='47.83' y='23.18' width='522.69' height='305.33'/>\\n  <\\/clipPath>\\n <\\/defs>\\n <g id='svg_07f55b258dd1de09_rootg' class='ggiraph-svg-rootg'>\\n  <g clip-path='url(#svg_07f55b258dd1de09_c1)'>\\n   <rect x='0' y='0' width='576' height='360' fill='#FFFFFF' fill-opacity='1' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.75' stroke-linejoin='round' stroke-linecap='round' class='ggiraph-svg-bg'/>\\n   <rect x='0' y='0' width='576' height='360' fill='#FFFFFF' fill-opacity='1' stroke='#FFFFFF' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='round'/>\\n  <\\/g>\\n  <g clip-path='url(#svg_07f55b258dd1de09_c2)'>\\n   <rect x='47.83' y='23.18' width='522.69' height='305.33' fill='#EBEBEB' fill-opacity='1' stroke='none'/>\\n   <polyline points='47.83,286.35 570.52,286.35' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.53' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='47.83,229.79 570.52,229.79' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.53' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='47.83,173.24 570.52,173.24' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.53' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='47.83,116.68 570.52,116.68' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.53' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='47.83,60.13 570.52,60.13' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.53' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='161.03,328.50 161.03,23.18' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.53' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='339.93,328.50 339.93,23.18' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.53' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='518.83,328.50 518.83,23.18' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.53' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='47.83,314.63 570.52,314.63' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='47.83,258.07 570.52,258.07' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='47.83,201.52 570.52,201.52' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='47.83,144.96 570.52,144.96' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='47.83,88.41 570.52,88.41' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='47.83,31.85 570.52,31.85' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='71.58,328.50 71.58,23.18' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='250.48,328.50 250.48,23.18' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='429.38,328.50 429.38,23.18' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <rect id='svg_07f55b258dd1de09_e1' x='71.58' y='37.06' width='15.84' height='277.57' fill='#ADD8E6' fill-opacity='1' stroke='#4D4D4D' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='miter' stroke-linecap='butt' title='Count: 24540&amp;lt;br&amp;gt;Transaction Value Range: 0 - 1770762'/>\\n   <rect id='svg_07f55b258dd1de09_e2' x='87.42' y='247.74' width='15.84' height='66.88' fill='#ADD8E6' fill-opacity='1' stroke='#4D4D4D' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='miter' stroke-linecap='butt' title='Count: 5913&amp;lt;br&amp;gt;Transaction Value Range: 1770762 - 3541523'/>\\n   <rect id='svg_07f55b258dd1de09_e3' x='103.26' y='198.35' width='15.84' height='116.28' fill='#ADD8E6' fill-opacity='1' stroke='#4D4D4D' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='miter' stroke-linecap='butt' title='Count: 10280&amp;lt;br&amp;gt;Transaction Value Range: 3541523 - 5312285'/>\\n   <rect id='svg_07f55b258dd1de09_e4' x='119.1' y='281.97' width='15.84' height='32.65' fill='#ADD8E6' fill-opacity='1' stroke='#4D4D4D' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='miter' stroke-linecap='butt' title='Count: 2887&amp;lt;br&amp;gt;Transaction Value Range: 5312285 - 7083047'/>\\n   <rect id='svg_07f55b258dd1de09_e5' x='134.94' y='310.69' width='15.84' height='3.94' fill='#ADD8E6' fill-opacity='1' stroke='#4D4D4D' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='miter' stroke-linecap='butt' title='Count: 348&amp;lt;br&amp;gt;Transaction Value Range: 7083047 - 8853808'/>\\n   <rect id='svg_07f55b258dd1de09_e6' x='150.78' y='309.38' width='15.84' height='5.25' fill='#ADD8E6' fill-opacity='1' stroke='#4D4D4D' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='miter' stroke-linecap='butt' title='Count: 464&amp;lt;br&amp;gt;Transaction Value Range: 8853808 - 10624570'/>\\n   <rect id='svg_07f55b258dd1de09_e7' x='166.62' y='304.19' width='15.84' height='10.44' fill='#ADD8E6' fill-opacity='1' stroke='#4D4D4D' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='miter' stroke-linecap='butt' title='Count: 923&amp;lt;br&amp;gt;Transaction Value Range: 10624570 - 12395332'/>\\n   <rect id='svg_07f55b258dd1de09_e8' x='182.46' y='298.71' width='15.84' height='15.91' fill='#ADD8E6' fill-opacity='1' stroke='#4D4D4D' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='miter' stroke-linecap='butt' title='Count: 1407&amp;lt;br&amp;gt;Transaction Value Range: 12395332 - 14166093'/>\\n   <rect id='svg_07f55b258dd1de09_e9' x='198.3' y='303.26' width='15.84' height='11.37' fill='#ADD8E6' fill-opacity='1' stroke='#4D4D4D' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='miter' stroke-linecap='butt' title='Count: 1005&amp;lt;br&amp;gt;Transaction Value Range: 14166093 - 15936855'/>\\n   <rect id='svg_07f55b258dd1de09_e10' x='214.14' y='309.29' width='15.84' height='5.34' fill='#ADD8E6' fill-opacity='1' stroke='#4D4D4D' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='miter' stroke-linecap='butt' title='Count: 472&amp;lt;br&amp;gt;Transaction Value Range: 15936855 - 17707616'/>\\n   <rect id='svg_07f55b258dd1de09_e11' x='229.98' y='311.77' width='15.84' height='2.85' fill='#ADD8E6' fill-opacity='1' stroke='#4D4D4D' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='miter' stroke-linecap='butt' title='Count: 252&amp;lt;br&amp;gt;Transaction Value Range: 17707616 - 19478378'/>\\n   <rect id='svg_07f55b258dd1de09_e12' x='245.82' y='313.38' width='15.84' height='1.24' fill='#ADD8E6' fill-opacity='1' stroke='#4D4D4D' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='miter' stroke-linecap='butt' title='Count: 110&amp;lt;br&amp;gt;Transaction Value Range: 19478378 - 21249140'/>\\n   <rect id='svg_07f55b258dd1de09_e13' x='261.66' y='314.04' width='15.84' height='0.59' fill='#ADD8E6' fill-opacity='1' stroke='#4D4D4D' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='miter' stroke-linecap='butt' title='Count: 52&amp;lt;br&amp;gt;Transaction Value Range: 21249140 - 23019901'/>\\n   <rect id='svg_07f55b258dd1de09_e14' x='277.49' y='314.29' width='15.84' height='0.34' fill='#ADD8E6' fill-opacity='1' stroke='#4D4D4D' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='miter' stroke-linecap='butt' title='Count: 30&amp;lt;br&amp;gt;Transaction Value Range: 23019901 - 24790663'/>\\n   <rect id='svg_07f55b258dd1de09_e15' x='293.33' y='314.42' width='15.84' height='0.2' fill='#ADD8E6' fill-opacity='1' stroke='#4D4D4D' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='miter' stroke-linecap='butt' title='Count: 18&amp;lt;br&amp;gt;Transaction Value Range: 24790663 - 26561425'/>\\n   <rect id='svg_07f55b258dd1de09_e16' x='309.17' y='314.52' width='15.84' height='0.1' fill='#ADD8E6' fill-opacity='1' stroke='#4D4D4D' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='miter' stroke-linecap='butt' title='Count: 9&amp;lt;br&amp;gt;Transaction Value Range: 26561425 - 28332186'/>\\n   <rect id='svg_07f55b258dd1de09_e17' x='325.01' y='314.6' width='15.84' height='0.02' fill='#ADD8E6' fill-opacity='1' stroke='#4D4D4D' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='miter' stroke-linecap='butt' title='Count: 2&amp;lt;br&amp;gt;Transaction Value Range: 28332186 - 30102948'/>\\n   <rect id='svg_07f55b258dd1de09_e18' x='340.85' y='314.57' width='15.84' height='0.06' fill='#ADD8E6' fill-opacity='1' stroke='#4D4D4D' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='miter' stroke-linecap='butt' title='Count: 5&amp;lt;br&amp;gt;Transaction Value Range: 30102948 - 31873710'/>\\n   <rect id='svg_07f55b258dd1de09_e19' x='356.69' y='314.6' width='15.84' height='0.02' fill='#ADD8E6' fill-opacity='1' stroke='#4D4D4D' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='miter' stroke-linecap='butt' title='Count: 2&amp;lt;br&amp;gt;Transaction Value Range: 31873710 - 33644471'/>\\n   <rect id='svg_07f55b258dd1de09_e20' x='372.53' y='314.63' width='15.84' height='0' fill='#ADD8E6' fill-opacity='1' stroke='#4D4D4D' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='miter' stroke-linecap='butt' title='Count: 0&amp;lt;br&amp;gt;Transaction Value Range: 33644471 - 35415233'/>\\n   <rect id='svg_07f55b258dd1de09_e21' x='388.37' y='314.6' width='15.84' height='0.02' fill='#ADD8E6' fill-opacity='1' stroke='#4D4D4D' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='miter' stroke-linecap='butt' title='Count: 2&amp;lt;br&amp;gt;Transaction Value Range: 35415233 - 37185995'/>\\n   <rect id='svg_07f55b258dd1de09_e22' x='404.21' y='314.61' width='15.84' height='0.01' fill='#ADD8E6' fill-opacity='1' stroke='#4D4D4D' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='miter' stroke-linecap='butt' title='Count: 1&amp;lt;br&amp;gt;Transaction Value Range: 37185995 - 38956756'/>\\n   <rect id='svg_07f55b258dd1de09_e23' x='420.05' y='314.63' width='15.84' height='0' fill='#ADD8E6' fill-opacity='1' stroke='#4D4D4D' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='miter' stroke-linecap='butt' title='Count: 0&amp;lt;br&amp;gt;Transaction Value Range: 38956756 - 40727518'/>\\n   <rect id='svg_07f55b258dd1de09_e24' x='435.89' y='314.63' width='15.84' height='0' fill='#ADD8E6' fill-opacity='1' stroke='#4D4D4D' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='miter' stroke-linecap='butt' title='Count: 0&amp;lt;br&amp;gt;Transaction Value Range: 40727518 - 42498280'/>\\n   <rect id='svg_07f55b258dd1de09_e25' x='451.73' y='314.63' width='15.84' height='0' fill='#ADD8E6' fill-opacity='1' stroke='#4D4D4D' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='miter' stroke-linecap='butt' title='Count: 0&amp;lt;br&amp;gt;Transaction Value Range: 42498280 - 44269041'/>\\n   <rect id='svg_07f55b258dd1de09_e26' x='467.57' y='314.63' width='15.84' height='0' fill='#ADD8E6' fill-opacity='1' stroke='#4D4D4D' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='miter' stroke-linecap='butt' title='Count: 0&amp;lt;br&amp;gt;Transaction Value Range: 44269041 - 46039803'/>\\n   <rect id='svg_07f55b258dd1de09_e27' x='483.4' y='314.63' width='15.84' height='0' fill='#ADD8E6' fill-opacity='1' stroke='#4D4D4D' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='miter' stroke-linecap='butt' title='Count: 0&amp;lt;br&amp;gt;Transaction Value Range: 46039803 - 47810564'/>\\n   <rect id='svg_07f55b258dd1de09_e28' x='499.24' y='314.63' width='15.84' height='0' fill='#ADD8E6' fill-opacity='1' stroke='#4D4D4D' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='miter' stroke-linecap='butt' title='Count: 0&amp;lt;br&amp;gt;Transaction Value Range: 47810564 - 49581326'/>\\n   <rect id='svg_07f55b258dd1de09_e29' x='515.08' y='314.63' width='15.84' height='0' fill='#ADD8E6' fill-opacity='1' stroke='#4D4D4D' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='miter' stroke-linecap='butt' title='Count: 0&amp;lt;br&amp;gt;Transaction Value Range: 49581326 - 51352088'/>\\n   <rect id='svg_07f55b258dd1de09_e30' x='530.92' y='314.61' width='15.84' height='0.01' fill='#ADD8E6' fill-opacity='1' stroke='#4D4D4D' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='miter' stroke-linecap='butt' title='Count: 1&amp;lt;br&amp;gt;Transaction Value Range: 51352088 - 53122849'/>\\n  <\\/g>\\n  <g clip-path='url(#svg_07f55b258dd1de09_c1)'>\\n   <text x='38' y='317.78' font-size='6.6pt' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>0<\\/text>\\n   <text x='23.31' y='261.22' font-size='6.6pt' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>5000<\\/text>\\n   <text x='18.41' y='204.67' font-size='6.6pt' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>10000<\\/text>\\n   <text x='18.41' y='148.11' font-size='6.6pt' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>15000<\\/text>\\n   <text x='18.41' y='91.56' font-size='6.6pt' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>20000<\\/text>\\n   <text x='18.41' y='35' font-size='6.6pt' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>25000<\\/text>\\n   <polyline points='45.09,314.63 47.83,314.63' fill='none' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='45.09,258.07 47.83,258.07' fill='none' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='45.09,201.52 47.83,201.52' fill='none' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='45.09,144.96 47.83,144.96' fill='none' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='45.09,88.41 47.83,88.41' fill='none' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='45.09,31.85 47.83,31.85' fill='none' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='71.58,331.24 71.58,328.50' fill='none' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='250.48,331.24 250.48,328.50' fill='none' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='429.38,331.24 429.38,328.50' fill='none' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <text x='59.22' y='339.74' font-size='6.6pt' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>0e+00<\\/text>\\n   <text x='238.12' y='339.74' font-size='6.6pt' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>2e+07<\\/text>\\n   <text x='417.02' y='339.74' font-size='6.6pt' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>4e+07<\\/text>\\n   <text x='243.62' y='352.2' font-size='8.25pt' font-family='Arial'>Average Transaction Value<\\/text>\\n   <text transform='translate(13.36,190.52) rotate(-90.00)' font-size='8.25pt' font-family='Arial'>Count<\\/text>\\n   <text x='47.83' y='14.93' font-size='9.9pt' font-family='Arial'>Distribution of Average Transaction Value<\\/text>\\n  <\\/g>\\n <\\/g>\\n<\\/svg>\",\"js\":null,\"uid\":\"svg_07f55b258dd1de09\",\"ratio\":1.6,\"settings\":{\"tooltip\":{\"css\":\".tooltip_SVGID_ { padding:5px;background:black;color:white;border-radius:2px;text-align:left; ; position:absolute;pointer-events:none;z-index:999;}\",\"placement\":\"doc\",\"opacity\":0.9,\"offx\":10,\"offy\":10,\"use_cursor_pos\":true,\"use_fill\":false,\"use_stroke\":false,\"delay_over\":200,\"delay_out\":500},\"hover\":{\"css\":\".hover_data_SVGID_ { fill:orange;stroke:black;cursor:pointer; }\\ntext.hover_data_SVGID_ { stroke:none;fill:orange; }\\ncircle.hover_data_SVGID_ { fill:orange;stroke:black; }\\nline.hover_data_SVGID_, polyline.hover_data_SVGID_ { fill:none;stroke:orange; }\\nrect.hover_data_SVGID_, polygon.hover_data_SVGID_, path.hover_data_SVGID_ { fill:orange;stroke:none; }\\nimage.hover_data_SVGID_ { stroke:orange; }\",\"reactive\":true,\"nearest_distance\":null},\"hover_inv\":{\"css\":\"\"},\"hover_key\":{\"css\":\".hover_key_SVGID_ { fill:orange;stroke:black;cursor:pointer; }\\ntext.hover_key_SVGID_ { stroke:none;fill:orange; }\\ncircle.hover_key_SVGID_ { fill:orange;stroke:black; }\\nline.hover_key_SVGID_, polyline.hover_key_SVGID_ { fill:none;stroke:orange; }\\nrect.hover_key_SVGID_, polygon.hover_key_SVGID_, path.hover_key_SVGID_ { fill:orange;stroke:none; }\\nimage.hover_key_SVGID_ { stroke:orange; }\",\"reactive\":true},\"hover_theme\":{\"css\":\".hover_theme_SVGID_ { fill:orange;stroke:black;cursor:pointer; }\\ntext.hover_theme_SVGID_ { stroke:none;fill:orange; }\\ncircle.hover_theme_SVGID_ { fill:orange;stroke:black; }\\nline.hover_theme_SVGID_, polyline.hover_theme_SVGID_ { fill:none;stroke:orange; }\\nrect.hover_theme_SVGID_, polygon.hover_theme_SVGID_, path.hover_theme_SVGID_ { fill:orange;stroke:none; }\\nimage.hover_theme_SVGID_ { stroke:orange; }\",\"reactive\":true},\"select\":{\"css\":\".select_data_SVGID_ { fill:red;stroke:black;cursor:pointer; }\\ntext.select_data_SVGID_ { stroke:none;fill:red; }\\ncircle.select_data_SVGID_ { fill:red;stroke:black; }\\nline.select_data_SVGID_, polyline.select_data_SVGID_ { fill:none;stroke:red; }\\nrect.select_data_SVGID_, polygon.select_data_SVGID_, path.select_data_SVGID_ { fill:red;stroke:none; }\\nimage.select_data_SVGID_ { stroke:red; }\",\"type\":\"multiple\",\"only_shiny\":true,\"selected\":[]},\"select_inv\":{\"css\":\"\"},\"select_key\":{\"css\":\".select_key_SVGID_ { fill:red;stroke:black;cursor:pointer; }\\ntext.select_key_SVGID_ { stroke:none;fill:red; }\\ncircle.select_key_SVGID_ { fill:red;stroke:black; }\\nline.select_key_SVGID_, polyline.select_key_SVGID_ { fill:none;stroke:red; }\\nrect.select_key_SVGID_, polygon.select_key_SVGID_, path.select_key_SVGID_ { fill:red;stroke:none; }\\nimage.select_key_SVGID_ { stroke:red; }\",\"type\":\"single\",\"only_shiny\":true,\"selected\":[]},\"select_theme\":{\"css\":\".select_theme_SVGID_ { fill:red;stroke:black;cursor:pointer; }\\ntext.select_theme_SVGID_ { stroke:none;fill:red; }\\ncircle.select_theme_SVGID_ { fill:red;stroke:black; }\\nline.select_theme_SVGID_, polyline.select_theme_SVGID_ { fill:none;stroke:red; }\\nrect.select_theme_SVGID_, polygon.select_theme_SVGID_, path.select_theme_SVGID_ { fill:red;stroke:none; }\\nimage.select_theme_SVGID_ { stroke:red; }\",\"type\":\"single\",\"only_shiny\":true,\"selected\":[]},\"zoom\":{\"min\":1,\"max\":1,\"duration\":300,\"default_on\":false},\"toolbar\":{\"position\":\"topright\",\"pngname\":\"diagram\",\"tooltips\":null,\"fixed\":false,\"hidden\":[],\"delay_over\":200,\"delay_out\":500},\"sizing\":{\"rescale\":true,\"width\":1}}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np <- ggplot(df, aes(x = avg_tx_value)) +\n  geom_histogram(bins = 30,\n                 boundary = 0,\n                 fill = \"lightblue\",\n                 color = \"grey30\") +\n  labs(\n    title = \"Distribution of Average Transaction Value\",\n    x = \"Average Transaction Value\",\n    y = \"Count\"\n  )\nggplotly(p)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-edb3eeac39d13f6b3143\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-edb3eeac39d13f6b3143\">{\"x\":{\"data\":[{\"orientation\":\"v\",\"width\":[1770761.6475095784,1770761.6475095786,1770761.6475095786,1770761.6475095786,1770761.6475095786,1770761.6475095786,1770761.6475095786,1770761.6475095786,1770761.6475095786,1770761.6475095749,1770761.6475095749,1770761.6475095749,1770761.6475095749,1770761.6475095749,1770761.6475095749,1770761.6475095749,1770761.6475095749,1770761.6475095749,1770761.6475095749,1770761.6475095749,1770761.6475095749,1770761.6475095749,1770761.6475095749,1770761.6475095749,1770761.6475095749,1770761.6475095749,1770761.6475095749,1770761.6475095749,1770761.6475095749,1770761.6475095749],\"base\":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],\"x\":[885380.82375478919,2656142.4712643675,4426904.1187739456,6197665.7662835242,7968427.4137931019,9739189.0613026805,11509950.708812259,13280712.356321838,15051474.003831416,16822235.651340995,18592997.298850574,20363758.946360148,22134520.593869731,23905282.241379306,25676043.888888888,27446805.536398463,29217567.183908045,30988328.83141762,32759090.478927203,34529852.126436777,36300613.77394636,38071375.421455935,39842137.06896551,41612898.716475092,43383660.363984674,45154422.011494249,46925183.659003824,48695945.306513406,50466706.954022989,52237468.601532564],\"y\":[24540,5913,10280,2887,348,464,923,1407,1005,472,252,110,52,30,18,9,2,5,2,0,2,1,0,0,0,0,0,0,0,1],\"text\":[\"count: 24540<br />avg_tx_value:   885380.8\",\"count:  5913<br />avg_tx_value:  2656142.5\",\"count: 10280<br />avg_tx_value:  4426904.1\",\"count:  2887<br />avg_tx_value:  6197665.8\",\"count:   348<br />avg_tx_value:  7968427.4\",\"count:   464<br />avg_tx_value:  9739189.1\",\"count:   923<br />avg_tx_value: 11509950.7\",\"count:  1407<br />avg_tx_value: 13280712.4\",\"count:  1005<br />avg_tx_value: 15051474.0\",\"count:   472<br />avg_tx_value: 16822235.7\",\"count:   252<br />avg_tx_value: 18592997.3\",\"count:   110<br />avg_tx_value: 20363758.9\",\"count:    52<br />avg_tx_value: 22134520.6\",\"count:    30<br />avg_tx_value: 23905282.2\",\"count:    18<br />avg_tx_value: 25676043.9\",\"count:     9<br />avg_tx_value: 27446805.5\",\"count:     2<br />avg_tx_value: 29217567.2\",\"count:     5<br />avg_tx_value: 30988328.8\",\"count:     2<br />avg_tx_value: 32759090.5\",\"count:     0<br />avg_tx_value: 34529852.1\",\"count:     2<br />avg_tx_value: 36300613.8\",\"count:     1<br />avg_tx_value: 38071375.4\",\"count:     0<br />avg_tx_value: 39842137.1\",\"count:     0<br />avg_tx_value: 41612898.7\",\"count:     0<br />avg_tx_value: 43383660.4\",\"count:     0<br />avg_tx_value: 45154422.0\",\"count:     0<br />avg_tx_value: 46925183.7\",\"count:     0<br />avg_tx_value: 48695945.3\",\"count:     0<br />avg_tx_value: 50466707.0\",\"count:     1<br />avg_tx_value: 52237468.6\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(173,216,230,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(77,77,77,1)\"}},\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":40.840182648401829,\"r\":7.3059360730593621,\"b\":37.260273972602747,\"l\":54.794520547945211},\"plot_bgcolor\":\"rgba(235,235,235,1)\",\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"title\":{\"text\":\"Distribution of Average Transaction Value\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":17.534246575342465},\"x\":0,\"xref\":\"paper\"},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-2656142.4712643679,55778991.896551721],\"tickmode\":\"array\",\"ticktext\":[\"0e+00\",\"2e+07\",\"4e+07\"],\"tickvals\":[0,20000000,40000000],\"categoryorder\":\"array\",\"categoryarray\":[\"0e+00\",\"2e+07\",\"4e+07\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.66417600664176002,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(255,255,255,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"Average Transaction Value\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-1227,25767],\"tickmode\":\"array\",\"ticktext\":[\"0\",\"5000\",\"10000\",\"15000\",\"20000\",\"25000\"],\"tickvals\":[0,5000,10000,15000,20000,25000],\"categoryorder\":\"array\",\"categoryarray\":[\"0\",\"5000\",\"10000\",\"15000\",\"20000\",\"25000\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.66417600664176002,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(255,255,255,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Count\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"shapes\":[],\"showlegend\":false,\"legend\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":1.8897637795275593,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.68949771689498}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"19283648188a\":{\"x\":{},\"type\":\"bar\"}},\"cur_data\":\"19283648188a\",\"visdat\":{\"19283648188a\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n3.  **Density Plot**\n\n\n::: {.cell}\n\n```{.r .cell-code}\np <- ggplot(df, aes(x = avg_tx_value)) +\n  geom_density(\n    fill = \"lightblue\",\n    alpha = 0.5,\n    color = \"grey30\"\n  ) +\n  labs(\n    title = \"Density Distribution of Average Transaction Value\",\n    x = \"Average Transaction Value\",\n    y = \"Density\"\n  )\n\nggplotly(p)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-86668f929d7bde8828f0\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-86668f929d7bde8828f0\">{\"x\":{\"data\":[{\"x\":[318215,418708.32246140466,519201.64492280933,619694.96738421393,720188.28984561865,820681.61230702326,921174.93476842786,1021668.2572298326,1122161.5796912373,1222654.9021526417,1323148.2246140465,1423641.5470754511,1524134.8695368557,1624628.1919982603,1725121.5144596652,1825614.8369210698,1926108.1593824744,2026601.481843879,2127094.8043052834,2227588.1267666882,2328081.449228093,2428574.7716894974,2529068.0941509022,2629561.4166123071,2730054.7390737114,2830548.0615351163,2931041.3839965207,3031534.7064579255,3132028.0289193303,3232521.3513807347,3333014.6738421395,3433507.9963035439,3534001.3187649488,3634494.6412263536,3734987.963687758,3835481.2861491628,3935974.6086105672,4036467.931071972,4136961.2535333768,4237454.5759947812,4337947.8984561861,4438441.22091759,4538934.5433789948,4639427.8658403996,4739921.1883018045,4840414.5107632093,4940907.8332246142,5041401.1556860181,5141894.4781474229,5242387.8006088277,5342881.1230702326,5443374.4455316374,5543867.7679930413,5644361.0904544462,5744854.412915851,5845347.7353772558,5945841.0578386607,6046334.3803000646,6146827.7027614694,6247321.0252228742,6347814.3476842791,6448307.6701456839,6548800.9926070878,6649294.3150684927,6749787.6375298975,6850280.9599913023,6950774.2824527072,7051267.6049141111,7151760.9273755159,7252254.2498369208,7352747.5722983256,7453240.8947597304,7553734.2172211343,7654227.5396825392,7754720.862143944,7855214.1846053489,7955707.5070667537,8056200.8295281576,8156694.1519895624,8257187.4744509673,8357680.7969123721,8458174.119373776,8558667.4418351799,8659160.7642965857,8759654.0867579896,8860147.4092193954,8960640.7316807993,9061134.054142205,9161627.376603609,9262120.6990650129,9362614.0215264186,9463107.3439878225,9563600.6664492283,9664093.9889106322,9764587.3113720361,9865080.6338334419,9965573.9562948458,10066067.278756252,10166560.601217655,10267053.923679059,10367547.246140465,10468040.568601869,10568533.891063275,10669027.213524679,10769520.535986083,10870013.858447488,10970507.180908892,11071000.503370298,11171493.825831702,11271987.148293106,11372480.470754512,11472973.793215916,11573467.115677321,11673960.438138725,11774453.760600129,11874947.083061535,11975440.405522939,12075933.727984345,12176427.050445748,12276920.372907152,12377413.695368558,12477907.017829962,12578400.340291368,12678893.662752772,12779386.985214176,12879880.307675581,12980373.630136985,13080866.952598391,13181360.275059795,13281853.597521199,13382346.919982605,13482840.242444009,13583333.564905414,13683826.887366818,13784320.209828222,13884813.532289628,13985306.854751032,14085800.177212438,14186293.499673842,14286786.822135245,14387280.144596651,14487773.467058055,14588266.789519461,14688760.111980865,14789253.434442269,14889746.756903674,14990240.079365078,15090733.401826484,15191226.724287888,15291720.046749292,15392213.369210698,15492706.691672102,15593200.014133507,15693693.336594911,15794186.659056315,15894679.981517721,15995173.303979125,16095666.626440531,16196159.948901935,16296653.271363338,16397146.593824744,16497639.916286148,16598133.238747554,16698626.561208958,16799119.88367036,16899613.206131767,17000106.528593171,17100599.851054575,17201093.173515979,17301586.495977387,17402079.818438791,17502573.140900195,17603066.463361599,17703559.785823002,17804053.10828441,17904546.430745814,18005039.753207218,18105533.075668622,18206026.398130026,18306519.720591433,18407013.043052837,18507506.365514241,18607999.687975645,18708493.010437049,18808986.332898457,18909479.655359861,19009972.977821264,19110466.300282668,19210959.622744072,19311452.94520548,19411946.267666884,19512439.590128288,19612932.912589692,19713426.235051095,19813919.557512503,19914412.879973907,20014906.202435311,20115399.524896715,20215892.847358119,20316386.169819526,20416879.49228093,20517372.814742334,20617866.137203738,20718359.459665142,20818852.78212655,20919346.104587954,21019839.427049357,21120332.749510761,21220826.071972165,21321319.394433573,21421812.716894977,21522306.039356381,21622799.361817785,21723292.684279189,21823786.006740596,21924279.329202,22024772.651663404,22125265.974124808,22225759.296586212,22326252.619047619,22426745.941509023,22527239.263970427,22627732.586431831,22728225.908893235,22828719.231354643,22929212.553816047,23029705.87627745,23130199.198738854,23230692.521200258,23331185.843661666,23431679.16612307,23532172.488584474,23632665.811045878,23733159.133507282,23833652.455968689,23934145.778430093,24034639.100891497,24135132.423352901,24235625.745814305,24336119.068275712,24436612.390737116,24537105.71319852,24637599.035659924,24738092.358121328,24838585.680582736,24939079.00304414,25039572.325505544,25140065.647966947,25240558.970428351,25341052.292889759,25441545.615351163,25542038.937812567,25642532.260273971,25743025.582735375,25843518.905196782,25944012.227658186,26044505.55011959,26144998.872580994,26245492.195042398,26345985.517503805,26446478.839965209,26546972.162426613,26647465.484888017,26747958.807349421,26848452.129810829,26948945.452272233,27049438.774733637,27149932.09719504,27250425.419656444,27350918.742117852,27451412.064579256,27551905.38704066,27652398.709502064,27752892.031963468,27853385.354424875,27953878.676886279,28054371.999347683,28154865.321809087,28255358.644270491,28355851.966731898,28456345.289193302,28556838.611654706,28657331.93411611,28757825.256577514,28858318.579038922,28958811.901500326,29059305.22396173,29159798.546423133,29260291.868884537,29360785.191345945,29461278.513807349,29561771.836268753,29662265.158730157,29762758.481191561,29863251.803652968,29963745.126114372,30064238.448575776,30164731.77103718,30265225.093498584,30365718.415959992,30466211.738421395,30566705.060882799,30667198.383344203,30767691.705805607,30868185.028267015,30968678.350728419,31069171.673189823,31169664.995651226,31270158.31811263,31370651.640574038,31471144.963035442,31571638.285496846,31672131.60795825,31772624.930419654,31873118.252881061,31973611.575342465,32074104.897803869,32174598.220265273,32275091.542726677,32375584.865188085,32476078.187649488,32576571.510110892,32677064.832572296,32777558.1550337,32878051.477495108,32978544.799956512,33079038.122417916,33179531.44487932,33280024.767340723,33380518.089802131,33481011.412263535,33581504.734724939,33681998.057186343,33782491.379647747,33882984.702109151,33983478.024570554,34083971.347031958,34184464.66949337,34284957.991954774,34385451.314416178,34485944.636877581,34586437.959338985,34686931.281800389,34787424.604261793,34887917.926723197,34988411.249184601,35088904.571646005,35189397.894107416,35289891.21656882,35390384.539030224,35490877.861491628,35591371.183953032,35691864.506414436,35792357.82887584,35892851.151337244,35993344.473798648,36093837.796260051,36194331.118721463,36294824.441182867,36395317.763644271,36495811.086105675,36596304.408567078,36696797.731028482,36797291.053489886,36897784.37595129,36998277.698412694,37098771.020874098,37199264.343335509,37299757.665796913,37400250.988258317,37500744.310719721,37601237.633181125,37701730.955642529,37802224.278103933,37902717.600565337,38003210.923026741,38103704.245488144,38204197.567949556,38304690.89041096,38405184.212872364,38505677.535333768,38606170.857795171,38706664.180256575,38807157.502717979,38907650.825179383,39008144.147640787,39108637.470102191,39209130.792563602,39309624.115025006,39410117.43748641,39510610.759947814,39611104.082409218,39711597.404870622,39812090.727332026,39912584.04979343,40013077.372254834,40113570.694716237,40214064.017177649,40314557.339639053,40415050.662100457,40515543.984561861,40616037.307023264,40716530.629484668,40817023.951946072,40917517.274407476,41018010.59686888,41118503.919330284,41218997.241791695,41319490.564253099,41419983.886714503,41520477.209175907,41620970.531637311,41721463.854098715,41821957.176560119,41922450.499021523,42022943.821482927,42123437.143944331,42223930.466405742,42324423.788867146,42424917.11132855,42525410.433789954,42625903.756251357,42726397.078712761,42826890.401174165,42927383.723635569,43027877.046096973,43128370.368558377,43228863.691019788,43329357.013481192,43429850.335942596,43530343.658404,43630836.980865404,43731330.303326808,43831823.625788212,43932316.948249616,44032810.27071102,44133303.593172424,44233796.915633835,44334290.238095239,44434783.560556643,44535276.883018047,44635770.205479451,44736263.527940854,44836756.850402258,44937250.172863662,45037743.495325066,45138236.81778647,45238730.140247881,45339223.462709285,45439716.785170689,45540210.107632093,45640703.430093497,45741196.752554901,45841690.075016305,45942183.397477709,46042676.719939113,46143170.042400517,46243663.364861928,46344156.687323332,46444650.009784736,46545143.33224614,46645636.654707544,46746129.977168947,46846623.299630351,46947116.622091755,47047609.944553159,47148103.267014563,47248596.589475974,47349089.911937378,47449583.234398782,47550076.556860186,47650569.87932159,47751063.201782994,47851556.524244398,47952049.846705802,48052543.169167206,48153036.49162861,48253529.814090021,48354023.136551425,48454516.459012829,48555009.781474233,48655503.103935637,48755996.42639704,48856489.748858444,48956983.071319848,49057476.393781252,49157969.716242656,49258463.038704067,49358956.361165471,49459449.683626875,49559943.006088279,49660436.328549683,49760929.651011087,49861422.973472491,49961916.295933895,50062409.618395299,50162902.940856703,50263396.263318114,50363889.585779518,50464382.908240922,50564876.230702326,50665369.55316373,50765862.875625134,50866356.198086537,50966849.520547941,51067342.843009345,51167836.165470749,51268329.48793216,51368822.810393564,51469316.132854968,51569809.455316372,51670302.777777776,51670302.777777776,51670302.777777776,51569809.455316372,51469316.132854968,51368822.810393564,51268329.48793216,51167836.165470749,51067342.843009345,50966849.520547941,50866356.198086537,50765862.875625134,50665369.55316373,50564876.230702326,50464382.908240922,50363889.585779518,50263396.263318114,50162902.940856703,50062409.618395299,49961916.295933895,49861422.973472491,49760929.651011087,49660436.328549683,49559943.006088279,49459449.683626875,49358956.361165471,49258463.038704067,49157969.716242656,49057476.393781252,48956983.071319848,48856489.748858444,48755996.42639704,48655503.103935637,48555009.781474233,48454516.459012829,48354023.136551425,48253529.814090021,48153036.49162861,48052543.169167206,47952049.846705802,47851556.524244398,47751063.201782994,47650569.87932159,47550076.556860186,47449583.234398782,47349089.911937378,47248596.589475974,47148103.267014563,47047609.944553159,46947116.622091755,46846623.299630351,46746129.977168947,46645636.654707544,46545143.33224614,46444650.009784736,46344156.687323332,46243663.364861928,46143170.042400517,46042676.719939113,45942183.397477709,45841690.075016305,45741196.752554901,45640703.430093497,45540210.107632093,45439716.785170689,45339223.462709285,45238730.140247881,45138236.81778647,45037743.495325066,44937250.172863662,44836756.850402258,44736263.527940854,44635770.205479451,44535276.883018047,44434783.560556643,44334290.238095239,44233796.915633835,44133303.593172424,44032810.27071102,43932316.948249616,43831823.625788212,43731330.303326808,43630836.980865404,43530343.658404,43429850.335942596,43329357.013481192,43228863.691019788,43128370.368558377,43027877.046096973,42927383.723635569,42826890.401174165,42726397.078712761,42625903.756251357,42525410.433789954,42424917.11132855,42324423.788867146,42223930.466405742,42123437.143944331,42022943.821482927,41922450.499021523,41821957.176560119,41721463.854098715,41620970.531637311,41520477.209175907,41419983.886714503,41319490.564253099,41218997.241791695,41118503.919330284,41018010.59686888,40917517.274407476,40817023.951946072,40716530.629484668,40616037.307023264,40515543.984561861,40415050.662100457,40314557.339639053,40214064.017177649,40113570.694716237,40013077.372254834,39912584.04979343,39812090.727332026,39711597.404870622,39611104.082409218,39510610.759947814,39410117.43748641,39309624.115025006,39209130.792563602,39108637.470102191,39008144.147640787,38907650.825179383,38807157.502717979,38706664.180256575,38606170.857795171,38505677.535333768,38405184.212872364,38304690.89041096,38204197.567949556,38103704.245488144,38003210.923026741,37902717.600565337,37802224.278103933,37701730.955642529,37601237.633181125,37500744.310719721,37400250.988258317,37299757.665796913,37199264.343335509,37098771.020874098,36998277.698412694,36897784.37595129,36797291.053489886,36696797.731028482,36596304.408567078,36495811.086105675,36395317.763644271,36294824.441182867,36194331.118721463,36093837.796260051,35993344.473798648,35892851.151337244,35792357.82887584,35691864.506414436,35591371.183953032,35490877.861491628,35390384.539030224,35289891.21656882,35189397.894107416,35088904.571646005,34988411.249184601,34887917.926723197,34787424.604261793,34686931.281800389,34586437.959338985,34485944.636877581,34385451.314416178,34284957.991954774,34184464.66949337,34083971.347031958,33983478.024570554,33882984.702109151,33782491.379647747,33681998.057186343,33581504.734724939,33481011.412263535,33380518.089802131,33280024.767340723,33179531.44487932,33079038.122417916,32978544.799956512,32878051.477495108,32777558.1550337,32677064.832572296,32576571.510110892,32476078.187649488,32375584.865188085,32275091.542726677,32174598.220265273,32074104.897803869,31973611.575342465,31873118.252881061,31772624.930419654,31672131.60795825,31571638.285496846,31471144.963035442,31370651.640574038,31270158.31811263,31169664.995651226,31069171.673189823,30968678.350728419,30868185.028267015,30767691.705805607,30667198.383344203,30566705.060882799,30466211.738421395,30365718.415959992,30265225.093498584,30164731.77103718,30064238.448575776,29963745.126114372,29863251.803652968,29762758.481191561,29662265.158730157,29561771.836268753,29461278.513807349,29360785.191345945,29260291.868884537,29159798.546423133,29059305.22396173,28958811.901500326,28858318.579038922,28757825.256577514,28657331.93411611,28556838.611654706,28456345.289193302,28355851.966731898,28255358.644270491,28154865.321809087,28054371.999347683,27953878.676886279,27853385.354424875,27752892.031963468,27652398.709502064,27551905.38704066,27451412.064579256,27350918.742117852,27250425.419656444,27149932.09719504,27049438.774733637,26948945.452272233,26848452.129810829,26747958.807349421,26647465.484888017,26546972.162426613,26446478.839965209,26345985.517503805,26245492.195042398,26144998.872580994,26044505.55011959,25944012.227658186,25843518.905196782,25743025.582735375,25642532.260273971,25542038.937812567,25441545.615351163,25341052.292889759,25240558.970428351,25140065.647966947,25039572.325505544,24939079.00304414,24838585.680582736,24738092.358121328,24637599.035659924,24537105.71319852,24436612.390737116,24336119.068275712,24235625.745814305,24135132.423352901,24034639.100891497,23934145.778430093,23833652.455968689,23733159.133507282,23632665.811045878,23532172.488584474,23431679.16612307,23331185.843661666,23230692.521200258,23130199.198738854,23029705.87627745,22929212.553816047,22828719.231354643,22728225.908893235,22627732.586431831,22527239.263970427,22426745.941509023,22326252.619047619,22225759.296586212,22125265.974124808,22024772.651663404,21924279.329202,21823786.006740596,21723292.684279189,21622799.361817785,21522306.039356381,21421812.716894977,21321319.394433573,21220826.071972165,21120332.749510761,21019839.427049357,20919346.104587954,20818852.78212655,20718359.459665142,20617866.137203738,20517372.814742334,20416879.49228093,20316386.169819526,20215892.847358119,20115399.524896715,20014906.202435311,19914412.879973907,19813919.557512503,19713426.235051095,19612932.912589692,19512439.590128288,19411946.267666884,19311452.94520548,19210959.622744072,19110466.300282668,19009972.977821264,18909479.655359861,18808986.332898457,18708493.010437049,18607999.687975645,18507506.365514241,18407013.043052837,18306519.720591433,18206026.398130026,18105533.075668622,18005039.753207218,17904546.430745814,17804053.10828441,17703559.785823002,17603066.463361599,17502573.140900195,17402079.818438791,17301586.495977387,17201093.173515979,17100599.851054575,17000106.528593171,16899613.206131767,16799119.88367036,16698626.561208958,16598133.238747554,16497639.916286148,16397146.593824744,16296653.271363338,16196159.948901935,16095666.626440531,15995173.303979125,15894679.981517721,15794186.659056315,15693693.336594911,15593200.014133507,15492706.691672102,15392213.369210698,15291720.046749292,15191226.724287888,15090733.401826484,14990240.079365078,14889746.756903674,14789253.434442269,14688760.111980865,14588266.789519461,14487773.467058055,14387280.144596651,14286786.822135245,14186293.499673842,14085800.177212438,13985306.854751032,13884813.532289628,13784320.209828222,13683826.887366818,13583333.564905414,13482840.242444009,13382346.919982605,13281853.597521199,13181360.275059795,13080866.952598391,12980373.630136985,12879880.307675581,12779386.985214176,12678893.662752772,12578400.340291368,12477907.017829962,12377413.695368558,12276920.372907152,12176427.050445748,12075933.727984345,11975440.405522939,11874947.083061535,11774453.760600129,11673960.438138725,11573467.115677321,11472973.793215916,11372480.470754512,11271987.148293106,11171493.825831702,11071000.503370298,10970507.180908892,10870013.858447488,10769520.535986083,10669027.213524679,10568533.891063275,10468040.568601869,10367547.246140465,10267053.923679059,10166560.601217655,10066067.278756252,9965573.9562948458,9865080.6338334419,9764587.3113720361,9664093.9889106322,9563600.6664492283,9463107.3439878225,9362614.0215264186,9262120.6990650129,9161627.376603609,9061134.054142205,8960640.7316807993,8860147.4092193954,8759654.0867579896,8659160.7642965857,8558667.4418351799,8458174.119373776,8357680.7969123721,8257187.4744509673,8156694.1519895624,8056200.8295281576,7955707.5070667537,7855214.1846053489,7754720.862143944,7654227.5396825392,7553734.2172211343,7453240.8947597304,7352747.5722983256,7252254.2498369208,7151760.9273755159,7051267.6049141111,6950774.2824527072,6850280.9599913023,6749787.6375298975,6649294.3150684927,6548800.9926070878,6448307.6701456839,6347814.3476842791,6247321.0252228742,6146827.7027614694,6046334.3803000646,5945841.0578386607,5845347.7353772558,5744854.412915851,5644361.0904544462,5543867.7679930413,5443374.4455316374,5342881.1230702326,5242387.8006088277,5141894.4781474229,5041401.1556860181,4940907.8332246142,4840414.5107632093,4739921.1883018045,4639427.8658403996,4538934.5433789948,4438441.22091759,4337947.8984561861,4237454.5759947812,4136961.2535333768,4036467.931071972,3935974.6086105672,3835481.2861491628,3734987.963687758,3634494.6412263536,3534001.3187649488,3433507.9963035439,3333014.6738421395,3232521.3513807347,3132028.0289193303,3031534.7064579255,2931041.3839965207,2830548.0615351163,2730054.7390737114,2629561.4166123071,2529068.0941509022,2428574.7716894974,2328081.449228093,2227588.1267666882,2127094.8043052834,2026601.481843879,1926108.1593824744,1825614.8369210698,1725121.5144596652,1624628.1919982603,1524134.8695368557,1423641.5470754511,1323148.2246140465,1222654.9021526417,1122161.5796912373,1021668.2572298326,921174.93476842786,820681.61230702326,720188.28984561865,619694.96738421393,519201.64492280933,418708.32246140466,318215,318215],\"y\":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.1170296258076865e-11,2.8916268359930919e-11,2.3217397259738805e-11,1.6159366610134441e-11,9.7567536032575088e-12,5.1093792459865772e-12,2.3179165017185395e-12,9.0911909885708979e-13,3.0748592238187441e-13,8.9432767820007574e-14,2.2306778247235373e-14,4.7593501296333007e-15,8.6671662810138853e-16,1.3447282099167904e-16,1.7749426986125015e-17,1.9907984758085478e-18,1.8957014479153854e-19,1.5309464415388554e-20,1.0340966105030818e-21,6.1259785040398619e-23,4.1091312387856678e-25,4.9046110075265627e-24,1.8130142865709074e-26,5.5167915252023888e-24,5.1805742722620385e-24,8.3321398108942647e-24,2.3402475344660301e-24,1.0448875652896829e-24,2.3002901330051634e-25,6.1507440065036026e-24,2.5608094310770268e-24,0,0,0,0,0,0,0,0,1.0156048669694323e-24,2.1458578011060798e-24,1.7914632753979039e-24,4.2284339198627165e-24,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.7807987201225135e-24,1.2259624047127111e-24,0,0,0,0,0,0,0,0,1.2103555166946722e-24,4.2662451035406256e-24,0,9.4177705265074818e-26,7.6489690183070379e-25,0,0,0,0,0,0,2.4982738555355794e-24,7.2325592107359035e-25,0,0,0,0,0,0,3.0829080385065483e-25,3.3601515147117906e-25,0,0,0,0,0,1.7371171008482902e-24,6.7160059733619558e-24,2.2853095144864403e-24,2.4870904120824286e-24,2.1776837236164694e-23,1.4179661019288968e-23,6.3323549606553517e-26,1.3855084146553666e-23,1.1787214776224602e-24,4.9135349587721339e-24,8.8521863912437148e-25,6.9735027171372807e-24,1.342726484211993e-23,1.6390138843035336e-23,1.4967588594323524e-23,6.818414053819228e-24,2.1381224291294739e-24,7.3277110090420277e-24,1.0698758267505227e-23,1.0130662930424246e-23,3.8433496451877188e-23,5.4627386954590442e-22,7.6467011314879378e-21,9.1945746680995502e-20,9.4020625370757465e-19,8.1853560634696464e-18,6.0854410686536808e-17,3.8790197286426066e-16,2.1303512814354359e-15,1.0135757991204158e-14,4.2002499985763978e-14,1.5226063659893855e-13,4.8807315286940822e-13,1.4036908390030269e-12,3.4440335996405374e-12,7.2224217839765859e-12,1.2973952238411623e-11,2.0013166747517581e-11,2.6581130474970381e-11,3.0479515124188023e-11,3.0246891351519423e-11,2.6027636284095296e-11,1.9444368841642942e-11,1.2615497859637974e-11,7.104626504711083e-12,3.4691512718199453e-12,1.4690063851204897e-12,5.5166192529799989e-13,2.3684979907848907e-13,2.8516927790162203e-13,7.3300504696805488e-13,1.8886641720808559e-12,4.2782112649644406e-12,8.4341083226825365e-12,1.4460482301032052e-11,2.1541710007293105e-11,2.783675736853298e-11,3.1148969531475495e-11,3.0136722690182094e-11,2.5390679385806899e-11,1.9410427446023168e-11,1.4939992137386648e-11,1.391670159262424e-11,1.6776696212621182e-11,2.2290911755386974e-11,2.7974526767966972e-11,3.1130334563584265e-11,3.0159158780486223e-11,2.5323143673573465e-11,1.8406216721651409e-11,1.1570439031190233e-11,6.2811138374097398e-12,2.9386530352148788e-12,1.1821080671827173e-12,4.0784249064040127e-13,1.2040096507776037e-13,3.0349457499519089e-14,6.5203479573324967e-15,1.1921881204246832e-15,1.8529785801679339e-16,2.4515462605021492e-17,3.3023664312196518e-18,4.9195650169814849e-18,3.3189385904875242e-17,2.1787083628694472e-16,1.4035916307519279e-15,7.6777933957801651e-15,3.5690747457466089e-14,1.41156212071738e-13,4.7570930121557624e-13,1.3689323746090833e-12,3.3731810743533425e-12,7.1448348304834214e-12,1.3080325886576596e-11,2.0865170682883771e-11,2.935856650956231e-11,3.7129769721166057e-11,4.3376603100042248e-11,4.8444598361128574e-11,5.3409441938720419e-11,5.9050323186843794e-11,6.509183907191697e-11,7.0237100139305953e-11,7.2764577972032619e-11,7.1198284805165448e-11,6.4854242638413829e-11,5.4255794724746595e-11,4.1234400403387411e-11,2.84752138414702e-11,1.8657970956039843e-11,1.3827565953819055e-11,1.5034484886456817e-11,2.2021868307323577e-11,3.3462548199787451e-11,4.6707891299393347e-11,5.8385213170528208e-11,6.5736328629990161e-11,6.7799492075905704e-11,6.5479536179254582e-11,6.0568596784756788e-11,5.4731242771035426e-11,4.924737590292458e-11,4.5260174424154286e-11,4.3741382789803421e-11,4.4952058539099328e-11,4.7996728340674633e-11,5.1068006578002034e-11,5.2246371735692045e-11,5.0246600930516031e-11,4.4767841915089942e-11,3.6544802511235789e-11,2.720612516566134e-11,1.8862226731753599e-11,1.3467317299047752e-11,1.2258574973368897e-11,1.5505851228032911e-11,2.2587996668657448e-11,3.2126568330593478e-11,4.2764104086679016e-11,5.3889109449720137e-11,6.5372418808474856e-11,7.6612358864774613e-11,8.5804690743392913e-11,9.0490162191763607e-11,8.9242023161248383e-11,8.3213032391628165e-11,7.6265914438683844e-11,7.3376773301958962e-11,7.8133940033214629e-11,9.0833507966800299e-11,1.0844977400719326e-10,1.2652944830964451e-10,1.4159924594557244e-10,1.5234274380333377e-10,1.5907259253594484e-10,1.6261512050983016e-10,1.6386281572469497e-10,1.6391290792766554e-10,1.6382778874540619e-10,1.6393223609299167e-10,1.6383279211368533e-10,1.6374552791395678e-10,1.6579095057252807e-10,1.7294164051380224e-10,1.8584485017935721e-10,2.0173702049952003e-10,2.1608824787802405e-10,2.2606434317545175e-10,2.3291496513792116e-10,2.412273198105924e-10,2.5547804372364487e-10,2.7648956387695681e-10,3.0051110661374075e-10,3.2163637897995958e-10,3.3575199118157392e-10,3.4310826717198541e-10,3.4764718184938693e-10,3.5355803648680587e-10,3.6152381079250057e-10,3.6743174691159822e-10,3.6467549452100046e-10,3.4865407949621672e-10,3.2055442154186134e-10,2.8811823571083991e-10,2.6302057514034615e-10,2.5596350398243138e-10,2.7122688565972894e-10,3.0324797585165708e-10,3.3816322715795436e-10,3.6218349617965839e-10,3.7285780865974868e-10,3.7978269461178229e-10,3.9704894141160969e-10,4.3304557873104231e-10,4.8555450940673198e-10,5.4476857059436382e-10,6.0027976305946562e-10,6.4596500430052746e-10,6.7979688687263749e-10,7.0052585324236e-10,7.0575783126964883e-10,6.9416213956385727e-10,6.699403446027111e-10,6.445630145099724e-10,6.3257810200955921e-10,6.4379897477585409e-10,6.7802051686228157e-10,7.2648169513085011e-10,7.784431225856573e-10,8.2737391419263044e-10,8.7268851786065031e-10,9.1731335114526365e-10,9.6408173388450188e-10,1.0135485531464435e-09,1.0639979949998756e-09,1.1131666655573286e-09,1.160669244047129e-09,1.2089781038535461e-09,1.2630072955324326e-09,1.327936167484759e-09,1.4056763900190892e-09,1.4920654839261314e-09,1.5775202095220051e-09,1.6515402150407505e-09,1.7079831329421299e-09,1.7476576125389511e-09,1.7780718767276102e-09,1.8125513612729856e-09,1.8690455199623519e-09,1.9659642717509307e-09,2.1139057817570383e-09,2.3077662538082182e-09,2.5263765031043963e-09,2.7416842226227479e-09,2.9312007262620193e-09,3.0850723628909894e-09,3.2049937771475404e-09,3.2990449918292201e-09,3.3774121659918332e-09,3.4501348048182926e-09,3.5252947118266431e-09,3.605306782691905e-09,3.6842579856384001e-09,3.7500632421846859e-09,3.7925042012961295e-09,3.81542891888353e-09,3.8449486645271163e-09,3.9240333329401029e-09,4.0914487692249016e-09,4.3563600997538344e-09,4.6875843720875672e-09,5.028501842516032e-09,5.3290722203503826e-09,5.5722934162214356e-09,5.7773855370024671e-09,5.981379579170426e-09,6.2160197278302259e-09,6.4949259146191095e-09,6.8126757456397047e-09,7.1491356864331381e-09,7.4756974524763576e-09,7.7657648397028473e-09,8.0095187218412415e-09,8.2255371463682396e-09,8.4594605916221173e-09,8.7664146592334147e-09,9.1885923944413045e-09,9.7246962775903357e-09,1.0341769394667678e-08,1.0996338626108968e-08,1.1649622707006591e-08,1.2272076370831461e-08,1.284151397756386e-08,1.3344472422854443e-08,1.3782274524565848e-08,1.4174180979576466e-08,1.4550527118102188e-08,1.4937745722257694e-08,1.5345194113145518e-08,1.5762739698199038e-08,1.6168782369916263e-08,1.6539542116932118e-08,1.68509881290363e-08,1.7074875933894494e-08,1.7179709672860635e-08,1.7144751664084249e-08,1.698065620721879e-08,1.6737631481535434e-08,1.6486027018330678e-08,1.6275759614847643e-08,1.6103450631334958e-08,1.5916810631033311e-08,1.5653670555070739e-08,1.5297825866553671e-08,1.4877690512406614e-08,1.4434209825589005e-08,1.3996922020592305e-08,1.3582428240012559e-08,1.3202062885600552e-08,1.2861159276319571e-08,1.2552212517438194e-08,1.2255502636775314e-08,1.1950555373641962e-08,1.1627610361801008e-08,1.128843733570056e-08,1.0938288623513017e-08,1.058006009327581e-08,1.0217780797316284e-08,9.8640759812198428e-09,9.5391986137458515e-09,9.2568654515830127e-09,9.0083783302777487e-09,8.7633344566374895e-09,8.491147111732568e-09,8.1845770968097871e-09,7.8614136973899221e-09,7.5426929631538135e-09,7.2310104746191321e-09,6.9104540469724043e-09,6.5700190949731892e-09,6.2199560558336909e-09,5.884646968187423e-09,5.5829568330302489e-09,5.3149324094671532e-09,5.0663908960752441e-09,4.8244149314487019e-09,4.5872864539325336e-09,4.3608936571166386e-09,4.1489520671907744e-09,3.9493493481028174e-09,3.7597404584412833e-09,3.5842321518895576e-09,3.4325877465100801e-09,3.3131546263169916e-09,3.2282393828503574e-09,3.1771046136608282e-09,3.1619880077191576e-09,3.18845274519514e-09,3.2578322140246897e-09,3.359728375688906e-09,3.4757511785152034e-09,3.5968346144873778e-09,3.7411145444896573e-09,3.9530946336941131e-09,4.2854048546898138e-09,4.7566951204910087e-09,5.366066418132572e-09,6.1136792085105194e-09,7.0132352073574591e-09,8.0796823133150683e-09,9.3065700507881373e-09,1.0661711242275959e-08,1.2113318180226427e-08,1.3668418308932789e-08,1.5391820592986861e-08,1.7390477610871478e-08,1.9776832670480737e-08,2.2637567131231792e-08,2.6023493051195451e-08,2.9958692590519585e-08,3.4459573170022156e-08,3.9556526321271936e-08,4.5310884617085059e-08,5.1816079007812053e-08,5.9176813272847515e-08,6.7479153533603682e-08,7.677526471716963e-08,8.7079456303687631e-08,9.8325690681804934e-08,1.1024414949782059e-07,1.2216475480423244e-07,1.3302005934939133e-07,1.4164161683069943e-07,1.4708401377460982e-07,1.4888791628022075e-07,1.4713043421549602e-07,1.4229116959171714e-07,1.3505145112729759e-07,1.2612660339244859e-07,1.161647410899537e-07,1.0570019549724941e-07,9.5141701956573769e-08,8.4781924479069871e-08,7.4817993748411832e-08,6.5375152461945244e-08,5.6532354581450624e-08,4.8352676188485622e-08,4.0914531037180298e-08,3.4329966253013777e-08,2.8741563953148391e-08,2.4311766831715827e-08,2.1235741515523693e-08,1.9800983066466733e-08,2.0492992636481892e-08,2.4133545688236511e-08,3.2062890586913753e-08,4.66029944588202e-08,7.0323710930769243e-08,1.0620689864983549e-07,1.5634335883232836e-07,2.2006838680553032e-07,2.9204794989236959e-07,3.6168974264656769e-07,4.1514819967337853e-07,4.3983514003293973e-07,4.2951034662591211e-07,3.8729283444052318e-07,3.250876404515698e-07,2.5998243947632679e-07,2.0936092605654783e-07,1.861286586409868e-07,1.9463927407732841e-07,2.2811901379730351e-07,2.694426951517461e-07,2.9693713526801377e-07,2.939451422172286e-07,2.5698249037852864e-07,1.9679472984937937e-07,0],\"text\":[\"density: 1.967947e-07<br />avg_tx_value:   318215.0\",\"density: 2.569825e-07<br />avg_tx_value:   418708.3\",\"density: 2.939451e-07<br />avg_tx_value:   519201.6\",\"density: 2.969371e-07<br />avg_tx_value:   619695.0\",\"density: 2.694427e-07<br />avg_tx_value:   720188.3\",\"density: 2.281190e-07<br />avg_tx_value:   820681.6\",\"density: 1.946393e-07<br />avg_tx_value:   921174.9\",\"density: 1.861287e-07<br />avg_tx_value:  1021668.3\",\"density: 2.093609e-07<br />avg_tx_value:  1122161.6\",\"density: 2.599824e-07<br />avg_tx_value:  1222654.9\",\"density: 3.250876e-07<br />avg_tx_value:  1323148.2\",\"density: 3.872928e-07<br />avg_tx_value:  1423641.5\",\"density: 4.295103e-07<br />avg_tx_value:  1524134.9\",\"density: 4.398351e-07<br />avg_tx_value:  1624628.2\",\"density: 4.151482e-07<br />avg_tx_value:  1725121.5\",\"density: 3.616897e-07<br />avg_tx_value:  1825614.8\",\"density: 2.920479e-07<br />avg_tx_value:  1926108.2\",\"density: 2.200684e-07<br />avg_tx_value:  2026601.5\",\"density: 1.563434e-07<br />avg_tx_value:  2127094.8\",\"density: 1.062069e-07<br />avg_tx_value:  2227588.1\",\"density: 7.032371e-08<br />avg_tx_value:  2328081.4\",\"density: 4.660299e-08<br />avg_tx_value:  2428574.8\",\"density: 3.206289e-08<br />avg_tx_value:  2529068.1\",\"density: 2.413355e-08<br />avg_tx_value:  2629561.4\",\"density: 2.049299e-08<br />avg_tx_value:  2730054.7\",\"density: 1.980098e-08<br />avg_tx_value:  2830548.1\",\"density: 2.123574e-08<br />avg_tx_value:  2931041.4\",\"density: 2.431177e-08<br />avg_tx_value:  3031534.7\",\"density: 2.874156e-08<br />avg_tx_value:  3132028.0\",\"density: 3.432997e-08<br />avg_tx_value:  3232521.4\",\"density: 4.091453e-08<br />avg_tx_value:  3333014.7\",\"density: 4.835268e-08<br />avg_tx_value:  3433508.0\",\"density: 5.653235e-08<br />avg_tx_value:  3534001.3\",\"density: 6.537515e-08<br />avg_tx_value:  3634494.6\",\"density: 7.481799e-08<br />avg_tx_value:  3734988.0\",\"density: 8.478192e-08<br />avg_tx_value:  3835481.3\",\"density: 9.514170e-08<br />avg_tx_value:  3935974.6\",\"density: 1.057002e-07<br />avg_tx_value:  4036467.9\",\"density: 1.161647e-07<br />avg_tx_value:  4136961.3\",\"density: 1.261266e-07<br />avg_tx_value:  4237454.6\",\"density: 1.350515e-07<br />avg_tx_value:  4337947.9\",\"density: 1.422912e-07<br />avg_tx_value:  4438441.2\",\"density: 1.471304e-07<br />avg_tx_value:  4538934.5\",\"density: 1.488879e-07<br />avg_tx_value:  4639427.9\",\"density: 1.470840e-07<br />avg_tx_value:  4739921.2\",\"density: 1.416416e-07<br />avg_tx_value:  4840414.5\",\"density: 1.330201e-07<br />avg_tx_value:  4940907.8\",\"density: 1.221648e-07<br />avg_tx_value:  5041401.2\",\"density: 1.102441e-07<br />avg_tx_value:  5141894.5\",\"density: 9.832569e-08<br />avg_tx_value:  5242387.8\",\"density: 8.707946e-08<br />avg_tx_value:  5342881.1\",\"density: 7.677526e-08<br />avg_tx_value:  5443374.4\",\"density: 6.747915e-08<br />avg_tx_value:  5543867.8\",\"density: 5.917681e-08<br />avg_tx_value:  5644361.1\",\"density: 5.181608e-08<br />avg_tx_value:  5744854.4\",\"density: 4.531088e-08<br />avg_tx_value:  5845347.7\",\"density: 3.955653e-08<br />avg_tx_value:  5945841.1\",\"density: 3.445957e-08<br />avg_tx_value:  6046334.4\",\"density: 2.995869e-08<br />avg_tx_value:  6146827.7\",\"density: 2.602349e-08<br />avg_tx_value:  6247321.0\",\"density: 2.263757e-08<br />avg_tx_value:  6347814.3\",\"density: 1.977683e-08<br />avg_tx_value:  6448307.7\",\"density: 1.739048e-08<br />avg_tx_value:  6548801.0\",\"density: 1.539182e-08<br />avg_tx_value:  6649294.3\",\"density: 1.366842e-08<br />avg_tx_value:  6749787.6\",\"density: 1.211332e-08<br />avg_tx_value:  6850281.0\",\"density: 1.066171e-08<br />avg_tx_value:  6950774.3\",\"density: 9.306570e-09<br />avg_tx_value:  7051267.6\",\"density: 8.079682e-09<br />avg_tx_value:  7151760.9\",\"density: 7.013235e-09<br />avg_tx_value:  7252254.2\",\"density: 6.113679e-09<br />avg_tx_value:  7352747.6\",\"density: 5.366066e-09<br />avg_tx_value:  7453240.9\",\"density: 4.756695e-09<br />avg_tx_value:  7553734.2\",\"density: 4.285405e-09<br />avg_tx_value:  7654227.5\",\"density: 3.953095e-09<br />avg_tx_value:  7754720.9\",\"density: 3.741115e-09<br />avg_tx_value:  7855214.2\",\"density: 3.596835e-09<br />avg_tx_value:  7955707.5\",\"density: 3.475751e-09<br />avg_tx_value:  8056200.8\",\"density: 3.359728e-09<br />avg_tx_value:  8156694.2\",\"density: 3.257832e-09<br />avg_tx_value:  8257187.5\",\"density: 3.188453e-09<br />avg_tx_value:  8357680.8\",\"density: 3.161988e-09<br />avg_tx_value:  8458174.1\",\"density: 3.177105e-09<br />avg_tx_value:  8558667.4\",\"density: 3.228239e-09<br />avg_tx_value:  8659160.8\",\"density: 3.313155e-09<br />avg_tx_value:  8759654.1\",\"density: 3.432588e-09<br />avg_tx_value:  8860147.4\",\"density: 3.584232e-09<br />avg_tx_value:  8960640.7\",\"density: 3.759740e-09<br />avg_tx_value:  9061134.1\",\"density: 3.949349e-09<br />avg_tx_value:  9161627.4\",\"density: 4.148952e-09<br />avg_tx_value:  9262120.7\",\"density: 4.360894e-09<br />avg_tx_value:  9362614.0\",\"density: 4.587286e-09<br />avg_tx_value:  9463107.3\",\"density: 4.824415e-09<br />avg_tx_value:  9563600.7\",\"density: 5.066391e-09<br />avg_tx_value:  9664094.0\",\"density: 5.314932e-09<br />avg_tx_value:  9764587.3\",\"density: 5.582957e-09<br />avg_tx_value:  9865080.6\",\"density: 5.884647e-09<br />avg_tx_value:  9965574.0\",\"density: 6.219956e-09<br />avg_tx_value: 10066067.3\",\"density: 6.570019e-09<br />avg_tx_value: 10166560.6\",\"density: 6.910454e-09<br />avg_tx_value: 10267053.9\",\"density: 7.231010e-09<br />avg_tx_value: 10367547.2\",\"density: 7.542693e-09<br />avg_tx_value: 10468040.6\",\"density: 7.861414e-09<br />avg_tx_value: 10568533.9\",\"density: 8.184577e-09<br />avg_tx_value: 10669027.2\",\"density: 8.491147e-09<br />avg_tx_value: 10769520.5\",\"density: 8.763334e-09<br />avg_tx_value: 10870013.9\",\"density: 9.008378e-09<br />avg_tx_value: 10970507.2\",\"density: 9.256865e-09<br />avg_tx_value: 11071000.5\",\"density: 9.539199e-09<br />avg_tx_value: 11171493.8\",\"density: 9.864076e-09<br />avg_tx_value: 11271987.1\",\"density: 1.021778e-08<br />avg_tx_value: 11372480.5\",\"density: 1.058006e-08<br />avg_tx_value: 11472973.8\",\"density: 1.093829e-08<br />avg_tx_value: 11573467.1\",\"density: 1.128844e-08<br />avg_tx_value: 11673960.4\",\"density: 1.162761e-08<br />avg_tx_value: 11774453.8\",\"density: 1.195056e-08<br />avg_tx_value: 11874947.1\",\"density: 1.225550e-08<br />avg_tx_value: 11975440.4\",\"density: 1.255221e-08<br />avg_tx_value: 12075933.7\",\"density: 1.286116e-08<br />avg_tx_value: 12176427.1\",\"density: 1.320206e-08<br />avg_tx_value: 12276920.4\",\"density: 1.358243e-08<br />avg_tx_value: 12377413.7\",\"density: 1.399692e-08<br />avg_tx_value: 12477907.0\",\"density: 1.443421e-08<br />avg_tx_value: 12578400.3\",\"density: 1.487769e-08<br />avg_tx_value: 12678893.7\",\"density: 1.529783e-08<br />avg_tx_value: 12779387.0\",\"density: 1.565367e-08<br />avg_tx_value: 12879880.3\",\"density: 1.591681e-08<br />avg_tx_value: 12980373.6\",\"density: 1.610345e-08<br />avg_tx_value: 13080867.0\",\"density: 1.627576e-08<br />avg_tx_value: 13181360.3\",\"density: 1.648603e-08<br />avg_tx_value: 13281853.6\",\"density: 1.673763e-08<br />avg_tx_value: 13382346.9\",\"density: 1.698066e-08<br />avg_tx_value: 13482840.2\",\"density: 1.714475e-08<br />avg_tx_value: 13583333.6\",\"density: 1.717971e-08<br />avg_tx_value: 13683826.9\",\"density: 1.707488e-08<br />avg_tx_value: 13784320.2\",\"density: 1.685099e-08<br />avg_tx_value: 13884813.5\",\"density: 1.653954e-08<br />avg_tx_value: 13985306.9\",\"density: 1.616878e-08<br />avg_tx_value: 14085800.2\",\"density: 1.576274e-08<br />avg_tx_value: 14186293.5\",\"density: 1.534519e-08<br />avg_tx_value: 14286786.8\",\"density: 1.493775e-08<br />avg_tx_value: 14387280.1\",\"density: 1.455053e-08<br />avg_tx_value: 14487773.5\",\"density: 1.417418e-08<br />avg_tx_value: 14588266.8\",\"density: 1.378227e-08<br />avg_tx_value: 14688760.1\",\"density: 1.334447e-08<br />avg_tx_value: 14789253.4\",\"density: 1.284151e-08<br />avg_tx_value: 14889746.8\",\"density: 1.227208e-08<br />avg_tx_value: 14990240.1\",\"density: 1.164962e-08<br />avg_tx_value: 15090733.4\",\"density: 1.099634e-08<br />avg_tx_value: 15191226.7\",\"density: 1.034177e-08<br />avg_tx_value: 15291720.0\",\"density: 9.724696e-09<br />avg_tx_value: 15392213.4\",\"density: 9.188592e-09<br />avg_tx_value: 15492706.7\",\"density: 8.766415e-09<br />avg_tx_value: 15593200.0\",\"density: 8.459461e-09<br />avg_tx_value: 15693693.3\",\"density: 8.225537e-09<br />avg_tx_value: 15794186.7\",\"density: 8.009519e-09<br />avg_tx_value: 15894680.0\",\"density: 7.765765e-09<br />avg_tx_value: 15995173.3\",\"density: 7.475697e-09<br />avg_tx_value: 16095666.6\",\"density: 7.149136e-09<br />avg_tx_value: 16196159.9\",\"density: 6.812676e-09<br />avg_tx_value: 16296653.3\",\"density: 6.494926e-09<br />avg_tx_value: 16397146.6\",\"density: 6.216020e-09<br />avg_tx_value: 16497639.9\",\"density: 5.981380e-09<br />avg_tx_value: 16598133.2\",\"density: 5.777386e-09<br />avg_tx_value: 16698626.6\",\"density: 5.572293e-09<br />avg_tx_value: 16799119.9\",\"density: 5.329072e-09<br />avg_tx_value: 16899613.2\",\"density: 5.028502e-09<br />avg_tx_value: 17000106.5\",\"density: 4.687584e-09<br />avg_tx_value: 17100599.9\",\"density: 4.356360e-09<br />avg_tx_value: 17201093.2\",\"density: 4.091449e-09<br />avg_tx_value: 17301586.5\",\"density: 3.924033e-09<br />avg_tx_value: 17402079.8\",\"density: 3.844949e-09<br />avg_tx_value: 17502573.1\",\"density: 3.815429e-09<br />avg_tx_value: 17603066.5\",\"density: 3.792504e-09<br />avg_tx_value: 17703559.8\",\"density: 3.750063e-09<br />avg_tx_value: 17804053.1\",\"density: 3.684258e-09<br />avg_tx_value: 17904546.4\",\"density: 3.605307e-09<br />avg_tx_value: 18005039.8\",\"density: 3.525295e-09<br />avg_tx_value: 18105533.1\",\"density: 3.450135e-09<br />avg_tx_value: 18206026.4\",\"density: 3.377412e-09<br />avg_tx_value: 18306519.7\",\"density: 3.299045e-09<br />avg_tx_value: 18407013.0\",\"density: 3.204994e-09<br />avg_tx_value: 18507506.4\",\"density: 3.085072e-09<br />avg_tx_value: 18607999.7\",\"density: 2.931201e-09<br />avg_tx_value: 18708493.0\",\"density: 2.741684e-09<br />avg_tx_value: 18808986.3\",\"density: 2.526377e-09<br />avg_tx_value: 18909479.7\",\"density: 2.307766e-09<br />avg_tx_value: 19009973.0\",\"density: 2.113906e-09<br />avg_tx_value: 19110466.3\",\"density: 1.965964e-09<br />avg_tx_value: 19210959.6\",\"density: 1.869046e-09<br />avg_tx_value: 19311452.9\",\"density: 1.812551e-09<br />avg_tx_value: 19411946.3\",\"density: 1.778072e-09<br />avg_tx_value: 19512439.6\",\"density: 1.747658e-09<br />avg_tx_value: 19612932.9\",\"density: 1.707983e-09<br />avg_tx_value: 19713426.2\",\"density: 1.651540e-09<br />avg_tx_value: 19813919.6\",\"density: 1.577520e-09<br />avg_tx_value: 19914412.9\",\"density: 1.492065e-09<br />avg_tx_value: 20014906.2\",\"density: 1.405676e-09<br />avg_tx_value: 20115399.5\",\"density: 1.327936e-09<br />avg_tx_value: 20215892.8\",\"density: 1.263007e-09<br />avg_tx_value: 20316386.2\",\"density: 1.208978e-09<br />avg_tx_value: 20416879.5\",\"density: 1.160669e-09<br />avg_tx_value: 20517372.8\",\"density: 1.113167e-09<br />avg_tx_value: 20617866.1\",\"density: 1.063998e-09<br />avg_tx_value: 20718359.5\",\"density: 1.013549e-09<br />avg_tx_value: 20818852.8\",\"density: 9.640817e-10<br />avg_tx_value: 20919346.1\",\"density: 9.173134e-10<br />avg_tx_value: 21019839.4\",\"density: 8.726885e-10<br />avg_tx_value: 21120332.7\",\"density: 8.273739e-10<br />avg_tx_value: 21220826.1\",\"density: 7.784431e-10<br />avg_tx_value: 21321319.4\",\"density: 7.264817e-10<br />avg_tx_value: 21421812.7\",\"density: 6.780205e-10<br />avg_tx_value: 21522306.0\",\"density: 6.437990e-10<br />avg_tx_value: 21622799.4\",\"density: 6.325781e-10<br />avg_tx_value: 21723292.7\",\"density: 6.445630e-10<br />avg_tx_value: 21823786.0\",\"density: 6.699403e-10<br />avg_tx_value: 21924279.3\",\"density: 6.941621e-10<br />avg_tx_value: 22024772.7\",\"density: 7.057578e-10<br />avg_tx_value: 22125266.0\",\"density: 7.005259e-10<br />avg_tx_value: 22225759.3\",\"density: 6.797969e-10<br />avg_tx_value: 22326252.6\",\"density: 6.459650e-10<br />avg_tx_value: 22426745.9\",\"density: 6.002798e-10<br />avg_tx_value: 22527239.3\",\"density: 5.447686e-10<br />avg_tx_value: 22627732.6\",\"density: 4.855545e-10<br />avg_tx_value: 22728225.9\",\"density: 4.330456e-10<br />avg_tx_value: 22828719.2\",\"density: 3.970489e-10<br />avg_tx_value: 22929212.6\",\"density: 3.797827e-10<br />avg_tx_value: 23029705.9\",\"density: 3.728578e-10<br />avg_tx_value: 23130199.2\",\"density: 3.621835e-10<br />avg_tx_value: 23230692.5\",\"density: 3.381632e-10<br />avg_tx_value: 23331185.8\",\"density: 3.032480e-10<br />avg_tx_value: 23431679.2\",\"density: 2.712269e-10<br />avg_tx_value: 23532172.5\",\"density: 2.559635e-10<br />avg_tx_value: 23632665.8\",\"density: 2.630206e-10<br />avg_tx_value: 23733159.1\",\"density: 2.881182e-10<br />avg_tx_value: 23833652.5\",\"density: 3.205544e-10<br />avg_tx_value: 23934145.8\",\"density: 3.486541e-10<br />avg_tx_value: 24034639.1\",\"density: 3.646755e-10<br />avg_tx_value: 24135132.4\",\"density: 3.674317e-10<br />avg_tx_value: 24235625.7\",\"density: 3.615238e-10<br />avg_tx_value: 24336119.1\",\"density: 3.535580e-10<br />avg_tx_value: 24436612.4\",\"density: 3.476472e-10<br />avg_tx_value: 24537105.7\",\"density: 3.431083e-10<br />avg_tx_value: 24637599.0\",\"density: 3.357520e-10<br />avg_tx_value: 24738092.4\",\"density: 3.216364e-10<br />avg_tx_value: 24838585.7\",\"density: 3.005111e-10<br />avg_tx_value: 24939079.0\",\"density: 2.764896e-10<br />avg_tx_value: 25039572.3\",\"density: 2.554780e-10<br />avg_tx_value: 25140065.6\",\"density: 2.412273e-10<br />avg_tx_value: 25240559.0\",\"density: 2.329150e-10<br />avg_tx_value: 25341052.3\",\"density: 2.260643e-10<br />avg_tx_value: 25441545.6\",\"density: 2.160882e-10<br />avg_tx_value: 25542038.9\",\"density: 2.017370e-10<br />avg_tx_value: 25642532.3\",\"density: 1.858449e-10<br />avg_tx_value: 25743025.6\",\"density: 1.729416e-10<br />avg_tx_value: 25843518.9\",\"density: 1.657910e-10<br />avg_tx_value: 25944012.2\",\"density: 1.637455e-10<br />avg_tx_value: 26044505.6\",\"density: 1.638328e-10<br />avg_tx_value: 26144998.9\",\"density: 1.639322e-10<br />avg_tx_value: 26245492.2\",\"density: 1.638278e-10<br />avg_tx_value: 26345985.5\",\"density: 1.639129e-10<br />avg_tx_value: 26446478.8\",\"density: 1.638628e-10<br />avg_tx_value: 26546972.2\",\"density: 1.626151e-10<br />avg_tx_value: 26647465.5\",\"density: 1.590726e-10<br />avg_tx_value: 26747958.8\",\"density: 1.523427e-10<br />avg_tx_value: 26848452.1\",\"density: 1.415992e-10<br />avg_tx_value: 26948945.5\",\"density: 1.265294e-10<br />avg_tx_value: 27049438.8\",\"density: 1.084498e-10<br />avg_tx_value: 27149932.1\",\"density: 9.083351e-11<br />avg_tx_value: 27250425.4\",\"density: 7.813394e-11<br />avg_tx_value: 27350918.7\",\"density: 7.337677e-11<br />avg_tx_value: 27451412.1\",\"density: 7.626591e-11<br />avg_tx_value: 27551905.4\",\"density: 8.321303e-11<br />avg_tx_value: 27652398.7\",\"density: 8.924202e-11<br />avg_tx_value: 27752892.0\",\"density: 9.049016e-11<br />avg_tx_value: 27853385.4\",\"density: 8.580469e-11<br />avg_tx_value: 27953878.7\",\"density: 7.661236e-11<br />avg_tx_value: 28054372.0\",\"density: 6.537242e-11<br />avg_tx_value: 28154865.3\",\"density: 5.388911e-11<br />avg_tx_value: 28255358.6\",\"density: 4.276410e-11<br />avg_tx_value: 28355852.0\",\"density: 3.212657e-11<br />avg_tx_value: 28456345.3\",\"density: 2.258800e-11<br />avg_tx_value: 28556838.6\",\"density: 1.550585e-11<br />avg_tx_value: 28657331.9\",\"density: 1.225857e-11<br />avg_tx_value: 28757825.3\",\"density: 1.346732e-11<br />avg_tx_value: 28858318.6\",\"density: 1.886223e-11<br />avg_tx_value: 28958811.9\",\"density: 2.720613e-11<br />avg_tx_value: 29059305.2\",\"density: 3.654480e-11<br />avg_tx_value: 29159798.5\",\"density: 4.476784e-11<br />avg_tx_value: 29260291.9\",\"density: 5.024660e-11<br />avg_tx_value: 29360785.2\",\"density: 5.224637e-11<br />avg_tx_value: 29461278.5\",\"density: 5.106801e-11<br />avg_tx_value: 29561771.8\",\"density: 4.799673e-11<br />avg_tx_value: 29662265.2\",\"density: 4.495206e-11<br />avg_tx_value: 29762758.5\",\"density: 4.374138e-11<br />avg_tx_value: 29863251.8\",\"density: 4.526017e-11<br />avg_tx_value: 29963745.1\",\"density: 4.924738e-11<br />avg_tx_value: 30064238.4\",\"density: 5.473124e-11<br />avg_tx_value: 30164731.8\",\"density: 6.056860e-11<br />avg_tx_value: 30265225.1\",\"density: 6.547954e-11<br />avg_tx_value: 30365718.4\",\"density: 6.779949e-11<br />avg_tx_value: 30466211.7\",\"density: 6.573633e-11<br />avg_tx_value: 30566705.1\",\"density: 5.838521e-11<br />avg_tx_value: 30667198.4\",\"density: 4.670789e-11<br />avg_tx_value: 30767691.7\",\"density: 3.346255e-11<br />avg_tx_value: 30868185.0\",\"density: 2.202187e-11<br />avg_tx_value: 30968678.4\",\"density: 1.503448e-11<br />avg_tx_value: 31069171.7\",\"density: 1.382757e-11<br />avg_tx_value: 31169665.0\",\"density: 1.865797e-11<br />avg_tx_value: 31270158.3\",\"density: 2.847521e-11<br />avg_tx_value: 31370651.6\",\"density: 4.123440e-11<br />avg_tx_value: 31471145.0\",\"density: 5.425579e-11<br />avg_tx_value: 31571638.3\",\"density: 6.485424e-11<br />avg_tx_value: 31672131.6\",\"density: 7.119828e-11<br />avg_tx_value: 31772624.9\",\"density: 7.276458e-11<br />avg_tx_value: 31873118.3\",\"density: 7.023710e-11<br />avg_tx_value: 31973611.6\",\"density: 6.509184e-11<br />avg_tx_value: 32074104.9\",\"density: 5.905032e-11<br />avg_tx_value: 32174598.2\",\"density: 5.340944e-11<br />avg_tx_value: 32275091.5\",\"density: 4.844460e-11<br />avg_tx_value: 32375584.9\",\"density: 4.337660e-11<br />avg_tx_value: 32476078.2\",\"density: 3.712977e-11<br />avg_tx_value: 32576571.5\",\"density: 2.935857e-11<br />avg_tx_value: 32677064.8\",\"density: 2.086517e-11<br />avg_tx_value: 32777558.2\",\"density: 1.308033e-11<br />avg_tx_value: 32878051.5\",\"density: 7.144835e-12<br />avg_tx_value: 32978544.8\",\"density: 3.373181e-12<br />avg_tx_value: 33079038.1\",\"density: 1.368932e-12<br />avg_tx_value: 33179531.4\",\"density: 4.757093e-13<br />avg_tx_value: 33280024.8\",\"density: 1.411562e-13<br />avg_tx_value: 33380518.1\",\"density: 3.569075e-14<br />avg_tx_value: 33481011.4\",\"density: 7.677793e-15<br />avg_tx_value: 33581504.7\",\"density: 1.403592e-15<br />avg_tx_value: 33681998.1\",\"density: 2.178708e-16<br />avg_tx_value: 33782491.4\",\"density: 3.318939e-17<br />avg_tx_value: 33882984.7\",\"density: 4.919565e-18<br />avg_tx_value: 33983478.0\",\"density: 3.302366e-18<br />avg_tx_value: 34083971.3\",\"density: 2.451546e-17<br />avg_tx_value: 34184464.7\",\"density: 1.852979e-16<br />avg_tx_value: 34284958.0\",\"density: 1.192188e-15<br />avg_tx_value: 34385451.3\",\"density: 6.520348e-15<br />avg_tx_value: 34485944.6\",\"density: 3.034946e-14<br />avg_tx_value: 34586438.0\",\"density: 1.204010e-13<br />avg_tx_value: 34686931.3\",\"density: 4.078425e-13<br />avg_tx_value: 34787424.6\",\"density: 1.182108e-12<br />avg_tx_value: 34887917.9\",\"density: 2.938653e-12<br />avg_tx_value: 34988411.2\",\"density: 6.281114e-12<br />avg_tx_value: 35088904.6\",\"density: 1.157044e-11<br />avg_tx_value: 35189397.9\",\"density: 1.840622e-11<br />avg_tx_value: 35289891.2\",\"density: 2.532314e-11<br />avg_tx_value: 35390384.5\",\"density: 3.015916e-11<br />avg_tx_value: 35490877.9\",\"density: 3.113033e-11<br />avg_tx_value: 35591371.2\",\"density: 2.797453e-11<br />avg_tx_value: 35691864.5\",\"density: 2.229091e-11<br />avg_tx_value: 35792357.8\",\"density: 1.677670e-11<br />avg_tx_value: 35892851.2\",\"density: 1.391670e-11<br />avg_tx_value: 35993344.5\",\"density: 1.493999e-11<br />avg_tx_value: 36093837.8\",\"density: 1.941043e-11<br />avg_tx_value: 36194331.1\",\"density: 2.539068e-11<br />avg_tx_value: 36294824.4\",\"density: 3.013672e-11<br />avg_tx_value: 36395317.8\",\"density: 3.114897e-11<br />avg_tx_value: 36495811.1\",\"density: 2.783676e-11<br />avg_tx_value: 36596304.4\",\"density: 2.154171e-11<br />avg_tx_value: 36696797.7\",\"density: 1.446048e-11<br />avg_tx_value: 36797291.1\",\"density: 8.434108e-12<br />avg_tx_value: 36897784.4\",\"density: 4.278211e-12<br />avg_tx_value: 36998277.7\",\"density: 1.888664e-12<br />avg_tx_value: 37098771.0\",\"density: 7.330050e-13<br />avg_tx_value: 37199264.3\",\"density: 2.851693e-13<br />avg_tx_value: 37299757.7\",\"density: 2.368498e-13<br />avg_tx_value: 37400251.0\",\"density: 5.516619e-13<br />avg_tx_value: 37500744.3\",\"density: 1.469006e-12<br />avg_tx_value: 37601237.6\",\"density: 3.469151e-12<br />avg_tx_value: 37701731.0\",\"density: 7.104627e-12<br />avg_tx_value: 37802224.3\",\"density: 1.261550e-11<br />avg_tx_value: 37902717.6\",\"density: 1.944437e-11<br />avg_tx_value: 38003210.9\",\"density: 2.602764e-11<br />avg_tx_value: 38103704.2\",\"density: 3.024689e-11<br />avg_tx_value: 38204197.6\",\"density: 3.047952e-11<br />avg_tx_value: 38304690.9\",\"density: 2.658113e-11<br />avg_tx_value: 38405184.2\",\"density: 2.001317e-11<br />avg_tx_value: 38505677.5\",\"density: 1.297395e-11<br />avg_tx_value: 38606170.9\",\"density: 7.222422e-12<br />avg_tx_value: 38706664.2\",\"density: 3.444034e-12<br />avg_tx_value: 38807157.5\",\"density: 1.403691e-12<br />avg_tx_value: 38907650.8\",\"density: 4.880732e-13<br />avg_tx_value: 39008144.1\",\"density: 1.522606e-13<br />avg_tx_value: 39108637.5\",\"density: 4.200250e-14<br />avg_tx_value: 39209130.8\",\"density: 1.013576e-14<br />avg_tx_value: 39309624.1\",\"density: 2.130351e-15<br />avg_tx_value: 39410117.4\",\"density: 3.879020e-16<br />avg_tx_value: 39510610.8\",\"density: 6.085441e-17<br />avg_tx_value: 39611104.1\",\"density: 8.185356e-18<br />avg_tx_value: 39711597.4\",\"density: 9.402063e-19<br />avg_tx_value: 39812090.7\",\"density: 9.194575e-20<br />avg_tx_value: 39912584.0\",\"density: 7.646701e-21<br />avg_tx_value: 40013077.4\",\"density: 5.462739e-22<br />avg_tx_value: 40113570.7\",\"density: 3.843350e-23<br />avg_tx_value: 40214064.0\",\"density: 1.013066e-23<br />avg_tx_value: 40314557.3\",\"density: 1.069876e-23<br />avg_tx_value: 40415050.7\",\"density: 7.327711e-24<br />avg_tx_value: 40515544.0\",\"density: 2.138122e-24<br />avg_tx_value: 40616037.3\",\"density: 6.818414e-24<br />avg_tx_value: 40716530.6\",\"density: 1.496759e-23<br />avg_tx_value: 40817024.0\",\"density: 1.639014e-23<br />avg_tx_value: 40917517.3\",\"density: 1.342726e-23<br />avg_tx_value: 41018010.6\",\"density: 6.973503e-24<br />avg_tx_value: 41118503.9\",\"density: 8.852186e-25<br />avg_tx_value: 41218997.2\",\"density: 4.913535e-24<br />avg_tx_value: 41319490.6\",\"density: 1.178721e-24<br />avg_tx_value: 41419983.9\",\"density: 1.385508e-23<br />avg_tx_value: 41520477.2\",\"density: 6.332355e-26<br />avg_tx_value: 41620970.5\",\"density: 1.417966e-23<br />avg_tx_value: 41721463.9\",\"density: 2.177684e-23<br />avg_tx_value: 41821957.2\",\"density: 2.487090e-24<br />avg_tx_value: 41922450.5\",\"density: 2.285310e-24<br />avg_tx_value: 42022943.8\",\"density: 6.716006e-24<br />avg_tx_value: 42123437.1\",\"density: 1.737117e-24<br />avg_tx_value: 42223930.5\",\"density: 0.000000e+00<br />avg_tx_value: 42324423.8\",\"density: 0.000000e+00<br />avg_tx_value: 42424917.1\",\"density: 0.000000e+00<br />avg_tx_value: 42525410.4\",\"density: 0.000000e+00<br />avg_tx_value: 42625903.8\",\"density: 0.000000e+00<br />avg_tx_value: 42726397.1\",\"density: 3.360152e-25<br />avg_tx_value: 42826890.4\",\"density: 3.082908e-25<br />avg_tx_value: 42927383.7\",\"density: 0.000000e+00<br />avg_tx_value: 43027877.0\",\"density: 0.000000e+00<br />avg_tx_value: 43128370.4\",\"density: 0.000000e+00<br />avg_tx_value: 43228863.7\",\"density: 0.000000e+00<br />avg_tx_value: 43329357.0\",\"density: 0.000000e+00<br />avg_tx_value: 43429850.3\",\"density: 0.000000e+00<br />avg_tx_value: 43530343.7\",\"density: 7.232559e-25<br />avg_tx_value: 43630837.0\",\"density: 2.498274e-24<br />avg_tx_value: 43731330.3\",\"density: 0.000000e+00<br />avg_tx_value: 43831823.6\",\"density: 0.000000e+00<br />avg_tx_value: 43932316.9\",\"density: 0.000000e+00<br />avg_tx_value: 44032810.3\",\"density: 0.000000e+00<br />avg_tx_value: 44133303.6\",\"density: 0.000000e+00<br />avg_tx_value: 44233796.9\",\"density: 0.000000e+00<br />avg_tx_value: 44334290.2\",\"density: 7.648969e-25<br />avg_tx_value: 44434783.6\",\"density: 9.417771e-26<br />avg_tx_value: 44535276.9\",\"density: 0.000000e+00<br />avg_tx_value: 44635770.2\",\"density: 4.266245e-24<br />avg_tx_value: 44736263.5\",\"density: 1.210356e-24<br />avg_tx_value: 44836756.9\",\"density: 0.000000e+00<br />avg_tx_value: 44937250.2\",\"density: 0.000000e+00<br />avg_tx_value: 45037743.5\",\"density: 0.000000e+00<br />avg_tx_value: 45138236.8\",\"density: 0.000000e+00<br />avg_tx_value: 45238730.1\",\"density: 0.000000e+00<br />avg_tx_value: 45339223.5\",\"density: 0.000000e+00<br />avg_tx_value: 45439716.8\",\"density: 0.000000e+00<br />avg_tx_value: 45540210.1\",\"density: 0.000000e+00<br />avg_tx_value: 45640703.4\",\"density: 1.225962e-24<br />avg_tx_value: 45741196.8\",\"density: 1.780799e-24<br />avg_tx_value: 45841690.1\",\"density: 0.000000e+00<br />avg_tx_value: 45942183.4\",\"density: 0.000000e+00<br />avg_tx_value: 46042676.7\",\"density: 0.000000e+00<br />avg_tx_value: 46143170.0\",\"density: 0.000000e+00<br />avg_tx_value: 46243663.4\",\"density: 0.000000e+00<br />avg_tx_value: 46344156.7\",\"density: 0.000000e+00<br />avg_tx_value: 46444650.0\",\"density: 0.000000e+00<br />avg_tx_value: 46545143.3\",\"density: 0.000000e+00<br />avg_tx_value: 46645636.7\",\"density: 0.000000e+00<br />avg_tx_value: 46746130.0\",\"density: 0.000000e+00<br />avg_tx_value: 46846623.3\",\"density: 0.000000e+00<br />avg_tx_value: 46947116.6\",\"density: 0.000000e+00<br />avg_tx_value: 47047609.9\",\"density: 0.000000e+00<br />avg_tx_value: 47148103.3\",\"density: 0.000000e+00<br />avg_tx_value: 47248596.6\",\"density: 0.000000e+00<br />avg_tx_value: 47349089.9\",\"density: 4.228434e-24<br />avg_tx_value: 47449583.2\",\"density: 1.791463e-24<br />avg_tx_value: 47550076.6\",\"density: 2.145858e-24<br />avg_tx_value: 47650569.9\",\"density: 1.015605e-24<br />avg_tx_value: 47751063.2\",\"density: 0.000000e+00<br />avg_tx_value: 47851556.5\",\"density: 0.000000e+00<br />avg_tx_value: 47952049.8\",\"density: 0.000000e+00<br />avg_tx_value: 48052543.2\",\"density: 0.000000e+00<br />avg_tx_value: 48153036.5\",\"density: 0.000000e+00<br />avg_tx_value: 48253529.8\",\"density: 0.000000e+00<br />avg_tx_value: 48354023.1\",\"density: 0.000000e+00<br />avg_tx_value: 48454516.5\",\"density: 0.000000e+00<br />avg_tx_value: 48555009.8\",\"density: 2.560809e-24<br />avg_tx_value: 48655503.1\",\"density: 6.150744e-24<br />avg_tx_value: 48755996.4\",\"density: 2.300290e-25<br />avg_tx_value: 48856489.7\",\"density: 1.044888e-24<br />avg_tx_value: 48956983.1\",\"density: 2.340248e-24<br />avg_tx_value: 49057476.4\",\"density: 8.332140e-24<br />avg_tx_value: 49157969.7\",\"density: 5.180574e-24<br />avg_tx_value: 49258463.0\",\"density: 5.516792e-24<br />avg_tx_value: 49358956.4\",\"density: 1.813014e-26<br />avg_tx_value: 49459449.7\",\"density: 4.904611e-24<br />avg_tx_value: 49559943.0\",\"density: 4.109131e-25<br />avg_tx_value: 49660436.3\",\"density: 6.125979e-23<br />avg_tx_value: 49760929.7\",\"density: 1.034097e-21<br />avg_tx_value: 49861423.0\",\"density: 1.530946e-20<br />avg_tx_value: 49961916.3\",\"density: 1.895701e-19<br />avg_tx_value: 50062409.6\",\"density: 1.990798e-18<br />avg_tx_value: 50162902.9\",\"density: 1.774943e-17<br />avg_tx_value: 50263396.3\",\"density: 1.344728e-16<br />avg_tx_value: 50363889.6\",\"density: 8.667166e-16<br />avg_tx_value: 50464382.9\",\"density: 4.759350e-15<br />avg_tx_value: 50564876.2\",\"density: 2.230678e-14<br />avg_tx_value: 50665369.6\",\"density: 8.943277e-14<br />avg_tx_value: 50765862.9\",\"density: 3.074859e-13<br />avg_tx_value: 50866356.2\",\"density: 9.091191e-13<br />avg_tx_value: 50966849.5\",\"density: 2.317917e-12<br />avg_tx_value: 51067342.8\",\"density: 5.109379e-12<br />avg_tx_value: 51167836.2\",\"density: 9.756754e-12<br />avg_tx_value: 51268329.5\",\"density: 1.615937e-11<br />avg_tx_value: 51368822.8\",\"density: 2.321740e-11<br />avg_tx_value: 51469316.1\",\"density: 2.891627e-11<br />avg_tx_value: 51569809.5\",\"density: 3.117030e-11<br />avg_tx_value: 51670302.8\",\"density: 3.117030e-11<br />avg_tx_value: 51670302.8\",\"density: 3.117030e-11<br />avg_tx_value: 51670302.8\",\"density: 2.891627e-11<br />avg_tx_value: 51569809.5\",\"density: 2.321740e-11<br />avg_tx_value: 51469316.1\",\"density: 1.615937e-11<br />avg_tx_value: 51368822.8\",\"density: 9.756754e-12<br />avg_tx_value: 51268329.5\",\"density: 5.109379e-12<br />avg_tx_value: 51167836.2\",\"density: 2.317917e-12<br />avg_tx_value: 51067342.8\",\"density: 9.091191e-13<br />avg_tx_value: 50966849.5\",\"density: 3.074859e-13<br />avg_tx_value: 50866356.2\",\"density: 8.943277e-14<br />avg_tx_value: 50765862.9\",\"density: 2.230678e-14<br />avg_tx_value: 50665369.6\",\"density: 4.759350e-15<br />avg_tx_value: 50564876.2\",\"density: 8.667166e-16<br />avg_tx_value: 50464382.9\",\"density: 1.344728e-16<br />avg_tx_value: 50363889.6\",\"density: 1.774943e-17<br />avg_tx_value: 50263396.3\",\"density: 1.990798e-18<br />avg_tx_value: 50162902.9\",\"density: 1.895701e-19<br />avg_tx_value: 50062409.6\",\"density: 1.530946e-20<br />avg_tx_value: 49961916.3\",\"density: 1.034097e-21<br />avg_tx_value: 49861423.0\",\"density: 6.125979e-23<br />avg_tx_value: 49760929.7\",\"density: 4.109131e-25<br />avg_tx_value: 49660436.3\",\"density: 4.904611e-24<br />avg_tx_value: 49559943.0\",\"density: 1.813014e-26<br />avg_tx_value: 49459449.7\",\"density: 5.516792e-24<br />avg_tx_value: 49358956.4\",\"density: 5.180574e-24<br />avg_tx_value: 49258463.0\",\"density: 8.332140e-24<br />avg_tx_value: 49157969.7\",\"density: 2.340248e-24<br />avg_tx_value: 49057476.4\",\"density: 1.044888e-24<br />avg_tx_value: 48956983.1\",\"density: 2.300290e-25<br />avg_tx_value: 48856489.7\",\"density: 6.150744e-24<br />avg_tx_value: 48755996.4\",\"density: 2.560809e-24<br />avg_tx_value: 48655503.1\",\"density: 0.000000e+00<br />avg_tx_value: 48555009.8\",\"density: 0.000000e+00<br />avg_tx_value: 48454516.5\",\"density: 0.000000e+00<br />avg_tx_value: 48354023.1\",\"density: 0.000000e+00<br />avg_tx_value: 48253529.8\",\"density: 0.000000e+00<br />avg_tx_value: 48153036.5\",\"density: 0.000000e+00<br />avg_tx_value: 48052543.2\",\"density: 0.000000e+00<br />avg_tx_value: 47952049.8\",\"density: 0.000000e+00<br />avg_tx_value: 47851556.5\",\"density: 1.015605e-24<br />avg_tx_value: 47751063.2\",\"density: 2.145858e-24<br />avg_tx_value: 47650569.9\",\"density: 1.791463e-24<br />avg_tx_value: 47550076.6\",\"density: 4.228434e-24<br />avg_tx_value: 47449583.2\",\"density: 0.000000e+00<br />avg_tx_value: 47349089.9\",\"density: 0.000000e+00<br />avg_tx_value: 47248596.6\",\"density: 0.000000e+00<br />avg_tx_value: 47148103.3\",\"density: 0.000000e+00<br />avg_tx_value: 47047609.9\",\"density: 0.000000e+00<br />avg_tx_value: 46947116.6\",\"density: 0.000000e+00<br />avg_tx_value: 46846623.3\",\"density: 0.000000e+00<br />avg_tx_value: 46746130.0\",\"density: 0.000000e+00<br />avg_tx_value: 46645636.7\",\"density: 0.000000e+00<br />avg_tx_value: 46545143.3\",\"density: 0.000000e+00<br />avg_tx_value: 46444650.0\",\"density: 0.000000e+00<br />avg_tx_value: 46344156.7\",\"density: 0.000000e+00<br />avg_tx_value: 46243663.4\",\"density: 0.000000e+00<br />avg_tx_value: 46143170.0\",\"density: 0.000000e+00<br />avg_tx_value: 46042676.7\",\"density: 0.000000e+00<br />avg_tx_value: 45942183.4\",\"density: 1.780799e-24<br />avg_tx_value: 45841690.1\",\"density: 1.225962e-24<br />avg_tx_value: 45741196.8\",\"density: 0.000000e+00<br />avg_tx_value: 45640703.4\",\"density: 0.000000e+00<br />avg_tx_value: 45540210.1\",\"density: 0.000000e+00<br />avg_tx_value: 45439716.8\",\"density: 0.000000e+00<br />avg_tx_value: 45339223.5\",\"density: 0.000000e+00<br />avg_tx_value: 45238730.1\",\"density: 0.000000e+00<br />avg_tx_value: 45138236.8\",\"density: 0.000000e+00<br />avg_tx_value: 45037743.5\",\"density: 0.000000e+00<br />avg_tx_value: 44937250.2\",\"density: 1.210356e-24<br />avg_tx_value: 44836756.9\",\"density: 4.266245e-24<br />avg_tx_value: 44736263.5\",\"density: 0.000000e+00<br />avg_tx_value: 44635770.2\",\"density: 9.417771e-26<br />avg_tx_value: 44535276.9\",\"density: 7.648969e-25<br />avg_tx_value: 44434783.6\",\"density: 0.000000e+00<br />avg_tx_value: 44334290.2\",\"density: 0.000000e+00<br />avg_tx_value: 44233796.9\",\"density: 0.000000e+00<br />avg_tx_value: 44133303.6\",\"density: 0.000000e+00<br />avg_tx_value: 44032810.3\",\"density: 0.000000e+00<br />avg_tx_value: 43932316.9\",\"density: 0.000000e+00<br />avg_tx_value: 43831823.6\",\"density: 2.498274e-24<br />avg_tx_value: 43731330.3\",\"density: 7.232559e-25<br />avg_tx_value: 43630837.0\",\"density: 0.000000e+00<br />avg_tx_value: 43530343.7\",\"density: 0.000000e+00<br />avg_tx_value: 43429850.3\",\"density: 0.000000e+00<br />avg_tx_value: 43329357.0\",\"density: 0.000000e+00<br />avg_tx_value: 43228863.7\",\"density: 0.000000e+00<br />avg_tx_value: 43128370.4\",\"density: 0.000000e+00<br />avg_tx_value: 43027877.0\",\"density: 3.082908e-25<br />avg_tx_value: 42927383.7\",\"density: 3.360152e-25<br />avg_tx_value: 42826890.4\",\"density: 0.000000e+00<br />avg_tx_value: 42726397.1\",\"density: 0.000000e+00<br />avg_tx_value: 42625903.8\",\"density: 0.000000e+00<br />avg_tx_value: 42525410.4\",\"density: 0.000000e+00<br />avg_tx_value: 42424917.1\",\"density: 0.000000e+00<br />avg_tx_value: 42324423.8\",\"density: 1.737117e-24<br />avg_tx_value: 42223930.5\",\"density: 6.716006e-24<br />avg_tx_value: 42123437.1\",\"density: 2.285310e-24<br />avg_tx_value: 42022943.8\",\"density: 2.487090e-24<br />avg_tx_value: 41922450.5\",\"density: 2.177684e-23<br />avg_tx_value: 41821957.2\",\"density: 1.417966e-23<br />avg_tx_value: 41721463.9\",\"density: 6.332355e-26<br />avg_tx_value: 41620970.5\",\"density: 1.385508e-23<br />avg_tx_value: 41520477.2\",\"density: 1.178721e-24<br />avg_tx_value: 41419983.9\",\"density: 4.913535e-24<br />avg_tx_value: 41319490.6\",\"density: 8.852186e-25<br />avg_tx_value: 41218997.2\",\"density: 6.973503e-24<br />avg_tx_value: 41118503.9\",\"density: 1.342726e-23<br />avg_tx_value: 41018010.6\",\"density: 1.639014e-23<br />avg_tx_value: 40917517.3\",\"density: 1.496759e-23<br />avg_tx_value: 40817024.0\",\"density: 6.818414e-24<br />avg_tx_value: 40716530.6\",\"density: 2.138122e-24<br />avg_tx_value: 40616037.3\",\"density: 7.327711e-24<br />avg_tx_value: 40515544.0\",\"density: 1.069876e-23<br />avg_tx_value: 40415050.7\",\"density: 1.013066e-23<br />avg_tx_value: 40314557.3\",\"density: 3.843350e-23<br />avg_tx_value: 40214064.0\",\"density: 5.462739e-22<br />avg_tx_value: 40113570.7\",\"density: 7.646701e-21<br />avg_tx_value: 40013077.4\",\"density: 9.194575e-20<br />avg_tx_value: 39912584.0\",\"density: 9.402063e-19<br />avg_tx_value: 39812090.7\",\"density: 8.185356e-18<br />avg_tx_value: 39711597.4\",\"density: 6.085441e-17<br />avg_tx_value: 39611104.1\",\"density: 3.879020e-16<br />avg_tx_value: 39510610.8\",\"density: 2.130351e-15<br />avg_tx_value: 39410117.4\",\"density: 1.013576e-14<br />avg_tx_value: 39309624.1\",\"density: 4.200250e-14<br />avg_tx_value: 39209130.8\",\"density: 1.522606e-13<br />avg_tx_value: 39108637.5\",\"density: 4.880732e-13<br />avg_tx_value: 39008144.1\",\"density: 1.403691e-12<br />avg_tx_value: 38907650.8\",\"density: 3.444034e-12<br />avg_tx_value: 38807157.5\",\"density: 7.222422e-12<br />avg_tx_value: 38706664.2\",\"density: 1.297395e-11<br />avg_tx_value: 38606170.9\",\"density: 2.001317e-11<br />avg_tx_value: 38505677.5\",\"density: 2.658113e-11<br />avg_tx_value: 38405184.2\",\"density: 3.047952e-11<br />avg_tx_value: 38304690.9\",\"density: 3.024689e-11<br />avg_tx_value: 38204197.6\",\"density: 2.602764e-11<br />avg_tx_value: 38103704.2\",\"density: 1.944437e-11<br />avg_tx_value: 38003210.9\",\"density: 1.261550e-11<br />avg_tx_value: 37902717.6\",\"density: 7.104627e-12<br />avg_tx_value: 37802224.3\",\"density: 3.469151e-12<br />avg_tx_value: 37701731.0\",\"density: 1.469006e-12<br />avg_tx_value: 37601237.6\",\"density: 5.516619e-13<br />avg_tx_value: 37500744.3\",\"density: 2.368498e-13<br />avg_tx_value: 37400251.0\",\"density: 2.851693e-13<br />avg_tx_value: 37299757.7\",\"density: 7.330050e-13<br />avg_tx_value: 37199264.3\",\"density: 1.888664e-12<br />avg_tx_value: 37098771.0\",\"density: 4.278211e-12<br />avg_tx_value: 36998277.7\",\"density: 8.434108e-12<br />avg_tx_value: 36897784.4\",\"density: 1.446048e-11<br />avg_tx_value: 36797291.1\",\"density: 2.154171e-11<br />avg_tx_value: 36696797.7\",\"density: 2.783676e-11<br />avg_tx_value: 36596304.4\",\"density: 3.114897e-11<br />avg_tx_value: 36495811.1\",\"density: 3.013672e-11<br />avg_tx_value: 36395317.8\",\"density: 2.539068e-11<br />avg_tx_value: 36294824.4\",\"density: 1.941043e-11<br />avg_tx_value: 36194331.1\",\"density: 1.493999e-11<br />avg_tx_value: 36093837.8\",\"density: 1.391670e-11<br />avg_tx_value: 35993344.5\",\"density: 1.677670e-11<br />avg_tx_value: 35892851.2\",\"density: 2.229091e-11<br />avg_tx_value: 35792357.8\",\"density: 2.797453e-11<br />avg_tx_value: 35691864.5\",\"density: 3.113033e-11<br />avg_tx_value: 35591371.2\",\"density: 3.015916e-11<br />avg_tx_value: 35490877.9\",\"density: 2.532314e-11<br />avg_tx_value: 35390384.5\",\"density: 1.840622e-11<br />avg_tx_value: 35289891.2\",\"density: 1.157044e-11<br />avg_tx_value: 35189397.9\",\"density: 6.281114e-12<br />avg_tx_value: 35088904.6\",\"density: 2.938653e-12<br />avg_tx_value: 34988411.2\",\"density: 1.182108e-12<br />avg_tx_value: 34887917.9\",\"density: 4.078425e-13<br />avg_tx_value: 34787424.6\",\"density: 1.204010e-13<br />avg_tx_value: 34686931.3\",\"density: 3.034946e-14<br />avg_tx_value: 34586438.0\",\"density: 6.520348e-15<br />avg_tx_value: 34485944.6\",\"density: 1.192188e-15<br />avg_tx_value: 34385451.3\",\"density: 1.852979e-16<br />avg_tx_value: 34284958.0\",\"density: 2.451546e-17<br />avg_tx_value: 34184464.7\",\"density: 3.302366e-18<br />avg_tx_value: 34083971.3\",\"density: 4.919565e-18<br />avg_tx_value: 33983478.0\",\"density: 3.318939e-17<br />avg_tx_value: 33882984.7\",\"density: 2.178708e-16<br />avg_tx_value: 33782491.4\",\"density: 1.403592e-15<br />avg_tx_value: 33681998.1\",\"density: 7.677793e-15<br />avg_tx_value: 33581504.7\",\"density: 3.569075e-14<br />avg_tx_value: 33481011.4\",\"density: 1.411562e-13<br />avg_tx_value: 33380518.1\",\"density: 4.757093e-13<br />avg_tx_value: 33280024.8\",\"density: 1.368932e-12<br />avg_tx_value: 33179531.4\",\"density: 3.373181e-12<br />avg_tx_value: 33079038.1\",\"density: 7.144835e-12<br />avg_tx_value: 32978544.8\",\"density: 1.308033e-11<br />avg_tx_value: 32878051.5\",\"density: 2.086517e-11<br />avg_tx_value: 32777558.2\",\"density: 2.935857e-11<br />avg_tx_value: 32677064.8\",\"density: 3.712977e-11<br />avg_tx_value: 32576571.5\",\"density: 4.337660e-11<br />avg_tx_value: 32476078.2\",\"density: 4.844460e-11<br />avg_tx_value: 32375584.9\",\"density: 5.340944e-11<br />avg_tx_value: 32275091.5\",\"density: 5.905032e-11<br />avg_tx_value: 32174598.2\",\"density: 6.509184e-11<br />avg_tx_value: 32074104.9\",\"density: 7.023710e-11<br />avg_tx_value: 31973611.6\",\"density: 7.276458e-11<br />avg_tx_value: 31873118.3\",\"density: 7.119828e-11<br />avg_tx_value: 31772624.9\",\"density: 6.485424e-11<br />avg_tx_value: 31672131.6\",\"density: 5.425579e-11<br />avg_tx_value: 31571638.3\",\"density: 4.123440e-11<br />avg_tx_value: 31471145.0\",\"density: 2.847521e-11<br />avg_tx_value: 31370651.6\",\"density: 1.865797e-11<br />avg_tx_value: 31270158.3\",\"density: 1.382757e-11<br />avg_tx_value: 31169665.0\",\"density: 1.503448e-11<br />avg_tx_value: 31069171.7\",\"density: 2.202187e-11<br />avg_tx_value: 30968678.4\",\"density: 3.346255e-11<br />avg_tx_value: 30868185.0\",\"density: 4.670789e-11<br />avg_tx_value: 30767691.7\",\"density: 5.838521e-11<br />avg_tx_value: 30667198.4\",\"density: 6.573633e-11<br />avg_tx_value: 30566705.1\",\"density: 6.779949e-11<br />avg_tx_value: 30466211.7\",\"density: 6.547954e-11<br />avg_tx_value: 30365718.4\",\"density: 6.056860e-11<br />avg_tx_value: 30265225.1\",\"density: 5.473124e-11<br />avg_tx_value: 30164731.8\",\"density: 4.924738e-11<br />avg_tx_value: 30064238.4\",\"density: 4.526017e-11<br />avg_tx_value: 29963745.1\",\"density: 4.374138e-11<br />avg_tx_value: 29863251.8\",\"density: 4.495206e-11<br />avg_tx_value: 29762758.5\",\"density: 4.799673e-11<br />avg_tx_value: 29662265.2\",\"density: 5.106801e-11<br />avg_tx_value: 29561771.8\",\"density: 5.224637e-11<br />avg_tx_value: 29461278.5\",\"density: 5.024660e-11<br />avg_tx_value: 29360785.2\",\"density: 4.476784e-11<br />avg_tx_value: 29260291.9\",\"density: 3.654480e-11<br />avg_tx_value: 29159798.5\",\"density: 2.720613e-11<br />avg_tx_value: 29059305.2\",\"density: 1.886223e-11<br />avg_tx_value: 28958811.9\",\"density: 1.346732e-11<br />avg_tx_value: 28858318.6\",\"density: 1.225857e-11<br />avg_tx_value: 28757825.3\",\"density: 1.550585e-11<br />avg_tx_value: 28657331.9\",\"density: 2.258800e-11<br />avg_tx_value: 28556838.6\",\"density: 3.212657e-11<br />avg_tx_value: 28456345.3\",\"density: 4.276410e-11<br />avg_tx_value: 28355852.0\",\"density: 5.388911e-11<br />avg_tx_value: 28255358.6\",\"density: 6.537242e-11<br />avg_tx_value: 28154865.3\",\"density: 7.661236e-11<br />avg_tx_value: 28054372.0\",\"density: 8.580469e-11<br />avg_tx_value: 27953878.7\",\"density: 9.049016e-11<br />avg_tx_value: 27853385.4\",\"density: 8.924202e-11<br />avg_tx_value: 27752892.0\",\"density: 8.321303e-11<br />avg_tx_value: 27652398.7\",\"density: 7.626591e-11<br />avg_tx_value: 27551905.4\",\"density: 7.337677e-11<br />avg_tx_value: 27451412.1\",\"density: 7.813394e-11<br />avg_tx_value: 27350918.7\",\"density: 9.083351e-11<br />avg_tx_value: 27250425.4\",\"density: 1.084498e-10<br />avg_tx_value: 27149932.1\",\"density: 1.265294e-10<br />avg_tx_value: 27049438.8\",\"density: 1.415992e-10<br />avg_tx_value: 26948945.5\",\"density: 1.523427e-10<br />avg_tx_value: 26848452.1\",\"density: 1.590726e-10<br />avg_tx_value: 26747958.8\",\"density: 1.626151e-10<br />avg_tx_value: 26647465.5\",\"density: 1.638628e-10<br />avg_tx_value: 26546972.2\",\"density: 1.639129e-10<br />avg_tx_value: 26446478.8\",\"density: 1.638278e-10<br />avg_tx_value: 26345985.5\",\"density: 1.639322e-10<br />avg_tx_value: 26245492.2\",\"density: 1.638328e-10<br />avg_tx_value: 26144998.9\",\"density: 1.637455e-10<br />avg_tx_value: 26044505.6\",\"density: 1.657910e-10<br />avg_tx_value: 25944012.2\",\"density: 1.729416e-10<br />avg_tx_value: 25843518.9\",\"density: 1.858449e-10<br />avg_tx_value: 25743025.6\",\"density: 2.017370e-10<br />avg_tx_value: 25642532.3\",\"density: 2.160882e-10<br />avg_tx_value: 25542038.9\",\"density: 2.260643e-10<br />avg_tx_value: 25441545.6\",\"density: 2.329150e-10<br />avg_tx_value: 25341052.3\",\"density: 2.412273e-10<br />avg_tx_value: 25240559.0\",\"density: 2.554780e-10<br />avg_tx_value: 25140065.6\",\"density: 2.764896e-10<br />avg_tx_value: 25039572.3\",\"density: 3.005111e-10<br />avg_tx_value: 24939079.0\",\"density: 3.216364e-10<br />avg_tx_value: 24838585.7\",\"density: 3.357520e-10<br />avg_tx_value: 24738092.4\",\"density: 3.431083e-10<br />avg_tx_value: 24637599.0\",\"density: 3.476472e-10<br />avg_tx_value: 24537105.7\",\"density: 3.535580e-10<br />avg_tx_value: 24436612.4\",\"density: 3.615238e-10<br />avg_tx_value: 24336119.1\",\"density: 3.674317e-10<br />avg_tx_value: 24235625.7\",\"density: 3.646755e-10<br />avg_tx_value: 24135132.4\",\"density: 3.486541e-10<br />avg_tx_value: 24034639.1\",\"density: 3.205544e-10<br />avg_tx_value: 23934145.8\",\"density: 2.881182e-10<br />avg_tx_value: 23833652.5\",\"density: 2.630206e-10<br />avg_tx_value: 23733159.1\",\"density: 2.559635e-10<br />avg_tx_value: 23632665.8\",\"density: 2.712269e-10<br />avg_tx_value: 23532172.5\",\"density: 3.032480e-10<br />avg_tx_value: 23431679.2\",\"density: 3.381632e-10<br />avg_tx_value: 23331185.8\",\"density: 3.621835e-10<br />avg_tx_value: 23230692.5\",\"density: 3.728578e-10<br />avg_tx_value: 23130199.2\",\"density: 3.797827e-10<br />avg_tx_value: 23029705.9\",\"density: 3.970489e-10<br />avg_tx_value: 22929212.6\",\"density: 4.330456e-10<br />avg_tx_value: 22828719.2\",\"density: 4.855545e-10<br />avg_tx_value: 22728225.9\",\"density: 5.447686e-10<br />avg_tx_value: 22627732.6\",\"density: 6.002798e-10<br />avg_tx_value: 22527239.3\",\"density: 6.459650e-10<br />avg_tx_value: 22426745.9\",\"density: 6.797969e-10<br />avg_tx_value: 22326252.6\",\"density: 7.005259e-10<br />avg_tx_value: 22225759.3\",\"density: 7.057578e-10<br />avg_tx_value: 22125266.0\",\"density: 6.941621e-10<br />avg_tx_value: 22024772.7\",\"density: 6.699403e-10<br />avg_tx_value: 21924279.3\",\"density: 6.445630e-10<br />avg_tx_value: 21823786.0\",\"density: 6.325781e-10<br />avg_tx_value: 21723292.7\",\"density: 6.437990e-10<br />avg_tx_value: 21622799.4\",\"density: 6.780205e-10<br />avg_tx_value: 21522306.0\",\"density: 7.264817e-10<br />avg_tx_value: 21421812.7\",\"density: 7.784431e-10<br />avg_tx_value: 21321319.4\",\"density: 8.273739e-10<br />avg_tx_value: 21220826.1\",\"density: 8.726885e-10<br />avg_tx_value: 21120332.7\",\"density: 9.173134e-10<br />avg_tx_value: 21019839.4\",\"density: 9.640817e-10<br />avg_tx_value: 20919346.1\",\"density: 1.013549e-09<br />avg_tx_value: 20818852.8\",\"density: 1.063998e-09<br />avg_tx_value: 20718359.5\",\"density: 1.113167e-09<br />avg_tx_value: 20617866.1\",\"density: 1.160669e-09<br />avg_tx_value: 20517372.8\",\"density: 1.208978e-09<br />avg_tx_value: 20416879.5\",\"density: 1.263007e-09<br />avg_tx_value: 20316386.2\",\"density: 1.327936e-09<br />avg_tx_value: 20215892.8\",\"density: 1.405676e-09<br />avg_tx_value: 20115399.5\",\"density: 1.492065e-09<br />avg_tx_value: 20014906.2\",\"density: 1.577520e-09<br />avg_tx_value: 19914412.9\",\"density: 1.651540e-09<br />avg_tx_value: 19813919.6\",\"density: 1.707983e-09<br />avg_tx_value: 19713426.2\",\"density: 1.747658e-09<br />avg_tx_value: 19612932.9\",\"density: 1.778072e-09<br />avg_tx_value: 19512439.6\",\"density: 1.812551e-09<br />avg_tx_value: 19411946.3\",\"density: 1.869046e-09<br />avg_tx_value: 19311452.9\",\"density: 1.965964e-09<br />avg_tx_value: 19210959.6\",\"density: 2.113906e-09<br />avg_tx_value: 19110466.3\",\"density: 2.307766e-09<br />avg_tx_value: 19009973.0\",\"density: 2.526377e-09<br />avg_tx_value: 18909479.7\",\"density: 2.741684e-09<br />avg_tx_value: 18808986.3\",\"density: 2.931201e-09<br />avg_tx_value: 18708493.0\",\"density: 3.085072e-09<br />avg_tx_value: 18607999.7\",\"density: 3.204994e-09<br />avg_tx_value: 18507506.4\",\"density: 3.299045e-09<br />avg_tx_value: 18407013.0\",\"density: 3.377412e-09<br />avg_tx_value: 18306519.7\",\"density: 3.450135e-09<br />avg_tx_value: 18206026.4\",\"density: 3.525295e-09<br />avg_tx_value: 18105533.1\",\"density: 3.605307e-09<br />avg_tx_value: 18005039.8\",\"density: 3.684258e-09<br />avg_tx_value: 17904546.4\",\"density: 3.750063e-09<br />avg_tx_value: 17804053.1\",\"density: 3.792504e-09<br />avg_tx_value: 17703559.8\",\"density: 3.815429e-09<br />avg_tx_value: 17603066.5\",\"density: 3.844949e-09<br />avg_tx_value: 17502573.1\",\"density: 3.924033e-09<br />avg_tx_value: 17402079.8\",\"density: 4.091449e-09<br />avg_tx_value: 17301586.5\",\"density: 4.356360e-09<br />avg_tx_value: 17201093.2\",\"density: 4.687584e-09<br />avg_tx_value: 17100599.9\",\"density: 5.028502e-09<br />avg_tx_value: 17000106.5\",\"density: 5.329072e-09<br />avg_tx_value: 16899613.2\",\"density: 5.572293e-09<br />avg_tx_value: 16799119.9\",\"density: 5.777386e-09<br />avg_tx_value: 16698626.6\",\"density: 5.981380e-09<br />avg_tx_value: 16598133.2\",\"density: 6.216020e-09<br />avg_tx_value: 16497639.9\",\"density: 6.494926e-09<br />avg_tx_value: 16397146.6\",\"density: 6.812676e-09<br />avg_tx_value: 16296653.3\",\"density: 7.149136e-09<br />avg_tx_value: 16196159.9\",\"density: 7.475697e-09<br />avg_tx_value: 16095666.6\",\"density: 7.765765e-09<br />avg_tx_value: 15995173.3\",\"density: 8.009519e-09<br />avg_tx_value: 15894680.0\",\"density: 8.225537e-09<br />avg_tx_value: 15794186.7\",\"density: 8.459461e-09<br />avg_tx_value: 15693693.3\",\"density: 8.766415e-09<br />avg_tx_value: 15593200.0\",\"density: 9.188592e-09<br />avg_tx_value: 15492706.7\",\"density: 9.724696e-09<br />avg_tx_value: 15392213.4\",\"density: 1.034177e-08<br />avg_tx_value: 15291720.0\",\"density: 1.099634e-08<br />avg_tx_value: 15191226.7\",\"density: 1.164962e-08<br />avg_tx_value: 15090733.4\",\"density: 1.227208e-08<br />avg_tx_value: 14990240.1\",\"density: 1.284151e-08<br />avg_tx_value: 14889746.8\",\"density: 1.334447e-08<br />avg_tx_value: 14789253.4\",\"density: 1.378227e-08<br />avg_tx_value: 14688760.1\",\"density: 1.417418e-08<br />avg_tx_value: 14588266.8\",\"density: 1.455053e-08<br />avg_tx_value: 14487773.5\",\"density: 1.493775e-08<br />avg_tx_value: 14387280.1\",\"density: 1.534519e-08<br />avg_tx_value: 14286786.8\",\"density: 1.576274e-08<br />avg_tx_value: 14186293.5\",\"density: 1.616878e-08<br />avg_tx_value: 14085800.2\",\"density: 1.653954e-08<br />avg_tx_value: 13985306.9\",\"density: 1.685099e-08<br />avg_tx_value: 13884813.5\",\"density: 1.707488e-08<br />avg_tx_value: 13784320.2\",\"density: 1.717971e-08<br />avg_tx_value: 13683826.9\",\"density: 1.714475e-08<br />avg_tx_value: 13583333.6\",\"density: 1.698066e-08<br />avg_tx_value: 13482840.2\",\"density: 1.673763e-08<br />avg_tx_value: 13382346.9\",\"density: 1.648603e-08<br />avg_tx_value: 13281853.6\",\"density: 1.627576e-08<br />avg_tx_value: 13181360.3\",\"density: 1.610345e-08<br />avg_tx_value: 13080867.0\",\"density: 1.591681e-08<br />avg_tx_value: 12980373.6\",\"density: 1.565367e-08<br />avg_tx_value: 12879880.3\",\"density: 1.529783e-08<br />avg_tx_value: 12779387.0\",\"density: 1.487769e-08<br />avg_tx_value: 12678893.7\",\"density: 1.443421e-08<br />avg_tx_value: 12578400.3\",\"density: 1.399692e-08<br />avg_tx_value: 12477907.0\",\"density: 1.358243e-08<br />avg_tx_value: 12377413.7\",\"density: 1.320206e-08<br />avg_tx_value: 12276920.4\",\"density: 1.286116e-08<br />avg_tx_value: 12176427.1\",\"density: 1.255221e-08<br />avg_tx_value: 12075933.7\",\"density: 1.225550e-08<br />avg_tx_value: 11975440.4\",\"density: 1.195056e-08<br />avg_tx_value: 11874947.1\",\"density: 1.162761e-08<br />avg_tx_value: 11774453.8\",\"density: 1.128844e-08<br />avg_tx_value: 11673960.4\",\"density: 1.093829e-08<br />avg_tx_value: 11573467.1\",\"density: 1.058006e-08<br />avg_tx_value: 11472973.8\",\"density: 1.021778e-08<br />avg_tx_value: 11372480.5\",\"density: 9.864076e-09<br />avg_tx_value: 11271987.1\",\"density: 9.539199e-09<br />avg_tx_value: 11171493.8\",\"density: 9.256865e-09<br />avg_tx_value: 11071000.5\",\"density: 9.008378e-09<br />avg_tx_value: 10970507.2\",\"density: 8.763334e-09<br />avg_tx_value: 10870013.9\",\"density: 8.491147e-09<br />avg_tx_value: 10769520.5\",\"density: 8.184577e-09<br />avg_tx_value: 10669027.2\",\"density: 7.861414e-09<br />avg_tx_value: 10568533.9\",\"density: 7.542693e-09<br />avg_tx_value: 10468040.6\",\"density: 7.231010e-09<br />avg_tx_value: 10367547.2\",\"density: 6.910454e-09<br />avg_tx_value: 10267053.9\",\"density: 6.570019e-09<br />avg_tx_value: 10166560.6\",\"density: 6.219956e-09<br />avg_tx_value: 10066067.3\",\"density: 5.884647e-09<br />avg_tx_value:  9965574.0\",\"density: 5.582957e-09<br />avg_tx_value:  9865080.6\",\"density: 5.314932e-09<br />avg_tx_value:  9764587.3\",\"density: 5.066391e-09<br />avg_tx_value:  9664094.0\",\"density: 4.824415e-09<br />avg_tx_value:  9563600.7\",\"density: 4.587286e-09<br />avg_tx_value:  9463107.3\",\"density: 4.360894e-09<br />avg_tx_value:  9362614.0\",\"density: 4.148952e-09<br />avg_tx_value:  9262120.7\",\"density: 3.949349e-09<br />avg_tx_value:  9161627.4\",\"density: 3.759740e-09<br />avg_tx_value:  9061134.1\",\"density: 3.584232e-09<br />avg_tx_value:  8960640.7\",\"density: 3.432588e-09<br />avg_tx_value:  8860147.4\",\"density: 3.313155e-09<br />avg_tx_value:  8759654.1\",\"density: 3.228239e-09<br />avg_tx_value:  8659160.8\",\"density: 3.177105e-09<br />avg_tx_value:  8558667.4\",\"density: 3.161988e-09<br />avg_tx_value:  8458174.1\",\"density: 3.188453e-09<br />avg_tx_value:  8357680.8\",\"density: 3.257832e-09<br />avg_tx_value:  8257187.5\",\"density: 3.359728e-09<br />avg_tx_value:  8156694.2\",\"density: 3.475751e-09<br />avg_tx_value:  8056200.8\",\"density: 3.596835e-09<br />avg_tx_value:  7955707.5\",\"density: 3.741115e-09<br />avg_tx_value:  7855214.2\",\"density: 3.953095e-09<br />avg_tx_value:  7754720.9\",\"density: 4.285405e-09<br />avg_tx_value:  7654227.5\",\"density: 4.756695e-09<br />avg_tx_value:  7553734.2\",\"density: 5.366066e-09<br />avg_tx_value:  7453240.9\",\"density: 6.113679e-09<br />avg_tx_value:  7352747.6\",\"density: 7.013235e-09<br />avg_tx_value:  7252254.2\",\"density: 8.079682e-09<br />avg_tx_value:  7151760.9\",\"density: 9.306570e-09<br />avg_tx_value:  7051267.6\",\"density: 1.066171e-08<br />avg_tx_value:  6950774.3\",\"density: 1.211332e-08<br />avg_tx_value:  6850281.0\",\"density: 1.366842e-08<br />avg_tx_value:  6749787.6\",\"density: 1.539182e-08<br />avg_tx_value:  6649294.3\",\"density: 1.739048e-08<br />avg_tx_value:  6548801.0\",\"density: 1.977683e-08<br />avg_tx_value:  6448307.7\",\"density: 2.263757e-08<br />avg_tx_value:  6347814.3\",\"density: 2.602349e-08<br />avg_tx_value:  6247321.0\",\"density: 2.995869e-08<br />avg_tx_value:  6146827.7\",\"density: 3.445957e-08<br />avg_tx_value:  6046334.4\",\"density: 3.955653e-08<br />avg_tx_value:  5945841.1\",\"density: 4.531088e-08<br />avg_tx_value:  5845347.7\",\"density: 5.181608e-08<br />avg_tx_value:  5744854.4\",\"density: 5.917681e-08<br />avg_tx_value:  5644361.1\",\"density: 6.747915e-08<br />avg_tx_value:  5543867.8\",\"density: 7.677526e-08<br />avg_tx_value:  5443374.4\",\"density: 8.707946e-08<br />avg_tx_value:  5342881.1\",\"density: 9.832569e-08<br />avg_tx_value:  5242387.8\",\"density: 1.102441e-07<br />avg_tx_value:  5141894.5\",\"density: 1.221648e-07<br />avg_tx_value:  5041401.2\",\"density: 1.330201e-07<br />avg_tx_value:  4940907.8\",\"density: 1.416416e-07<br />avg_tx_value:  4840414.5\",\"density: 1.470840e-07<br />avg_tx_value:  4739921.2\",\"density: 1.488879e-07<br />avg_tx_value:  4639427.9\",\"density: 1.471304e-07<br />avg_tx_value:  4538934.5\",\"density: 1.422912e-07<br />avg_tx_value:  4438441.2\",\"density: 1.350515e-07<br />avg_tx_value:  4337947.9\",\"density: 1.261266e-07<br />avg_tx_value:  4237454.6\",\"density: 1.161647e-07<br />avg_tx_value:  4136961.3\",\"density: 1.057002e-07<br />avg_tx_value:  4036467.9\",\"density: 9.514170e-08<br />avg_tx_value:  3935974.6\",\"density: 8.478192e-08<br />avg_tx_value:  3835481.3\",\"density: 7.481799e-08<br />avg_tx_value:  3734988.0\",\"density: 6.537515e-08<br />avg_tx_value:  3634494.6\",\"density: 5.653235e-08<br />avg_tx_value:  3534001.3\",\"density: 4.835268e-08<br />avg_tx_value:  3433508.0\",\"density: 4.091453e-08<br />avg_tx_value:  3333014.7\",\"density: 3.432997e-08<br />avg_tx_value:  3232521.4\",\"density: 2.874156e-08<br />avg_tx_value:  3132028.0\",\"density: 2.431177e-08<br />avg_tx_value:  3031534.7\",\"density: 2.123574e-08<br />avg_tx_value:  2931041.4\",\"density: 1.980098e-08<br />avg_tx_value:  2830548.1\",\"density: 2.049299e-08<br />avg_tx_value:  2730054.7\",\"density: 2.413355e-08<br />avg_tx_value:  2629561.4\",\"density: 3.206289e-08<br />avg_tx_value:  2529068.1\",\"density: 4.660299e-08<br />avg_tx_value:  2428574.8\",\"density: 7.032371e-08<br />avg_tx_value:  2328081.4\",\"density: 1.062069e-07<br />avg_tx_value:  2227588.1\",\"density: 1.563434e-07<br />avg_tx_value:  2127094.8\",\"density: 2.200684e-07<br />avg_tx_value:  2026601.5\",\"density: 2.920479e-07<br />avg_tx_value:  1926108.2\",\"density: 3.616897e-07<br />avg_tx_value:  1825614.8\",\"density: 4.151482e-07<br />avg_tx_value:  1725121.5\",\"density: 4.398351e-07<br />avg_tx_value:  1624628.2\",\"density: 4.295103e-07<br />avg_tx_value:  1524134.9\",\"density: 3.872928e-07<br />avg_tx_value:  1423641.5\",\"density: 3.250876e-07<br />avg_tx_value:  1323148.2\",\"density: 2.599824e-07<br />avg_tx_value:  1222654.9\",\"density: 2.093609e-07<br />avg_tx_value:  1122161.6\",\"density: 1.861287e-07<br />avg_tx_value:  1021668.3\",\"density: 1.946393e-07<br />avg_tx_value:   921174.9\",\"density: 2.281190e-07<br />avg_tx_value:   820681.6\",\"density: 2.694427e-07<br />avg_tx_value:   720188.3\",\"density: 2.969371e-07<br />avg_tx_value:   619695.0\",\"density: 2.939451e-07<br />avg_tx_value:   519201.6\",\"density: 2.569825e-07<br />avg_tx_value:   418708.3\",\"density: 1.967947e-07<br />avg_tx_value:   318215.0\",\"density: 1.967947e-07<br />avg_tx_value:   318215.0\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(77,77,77,0.5)\",\"dash\":\"solid\"},\"fill\":\"toself\",\"fillcolor\":\"rgba(173,216,230,0.5)\",\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":40.840182648401829,\"r\":7.3059360730593621,\"b\":37.260273972602747,\"l\":54.794520547945211},\"plot_bgcolor\":\"rgba(235,235,235,1)\",\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"title\":{\"text\":\"Density Distribution of Average Transaction Value\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":17.534246575342465},\"x\":0,\"xref\":\"paper\"},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-2249389.388888889,54237907.166666664],\"tickmode\":\"array\",\"ticktext\":[\"0e+00\",\"1e+07\",\"2e+07\",\"3e+07\",\"4e+07\",\"5e+07\"],\"tickvals\":[0,10000000,20000000,29999999.999999996,40000000,50000000],\"categoryorder\":\"array\",\"categoryarray\":[\"0e+00\",\"1e+07\",\"2e+07\",\"3e+07\",\"4e+07\",\"5e+07\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.66417600664176002,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(255,255,255,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"Average Transaction Value\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-2.1991757001646987e-08,4.618268970345867e-07],\"tickmode\":\"array\",\"ticktext\":[\"0e+00\",\"1e-07\",\"2e-07\",\"3e-07\",\"4e-07\"],\"tickvals\":[0,1.0000000000000001e-07,1.9999999999999999e-07,2.9999999999999999e-07,3.9999999999999998e-07],\"categoryorder\":\"array\",\"categoryarray\":[\"0e+00\",\"1e-07\",\"2e-07\",\"3e-07\",\"4e-07\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.66417600664176002,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(255,255,255,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Density\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"shapes\":[],\"showlegend\":false,\"legend\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":1.8897637795275593,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.68949771689498}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"1928732f14c1\":{\"x\":{},\"type\":\"scatter\"}},\"cur_data\":\"1928732f14c1\",\"visdat\":{\"1928732f14c1\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n4.  **Boxplot**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(df, aes(x = \"\", y = app_store_rating)) +\n  geom_boxplot(fill = \"lightblue\") +\n  stat_summary(fun = median,\n               geom = \"point\",\n               colour = \"red\",\n               size = 4) +\n  labs(\n    y = \"App Store Rating\"\n  )\n```\n\n::: {.cell-output-display}\n![](THE02_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n### Text Analysis\n\nText analysis will be done using bar chart for the variables feature_requests and complaint_topics to understand the customers' sentiment towards the app.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfeature_data <- df %>%\n  select(feature_requests) %>%\n  filter(!is.na(feature_requests)) %>%\n  separate_rows(feature_requests, sep = \",\")\n\nfeature_data <- feature_data %>%\n  mutate(feature_requests = str_trim(feature_requests))\n\nfeature_counts <- feature_data %>%\n  count(feature_requests, sort = TRUE)\n\nfeature_counts %>%\n  slice_max(n, n = 10) %>%\n  ggplot(aes(x = reorder(feature_requests, n), y = n)) +\n  geom_col(fill = \"steelblue\") +\n  geom_text(aes(label = n), \n            hjust = -0.1, \n            size = 4) +\n  coord_flip() +\n  labs(\n    title = \"Most Requested Features\",\n    x = \"Feature Request\",\n    y = \"Frequency\"\n  ) \n```\n\n::: {.cell-output-display}\n![](THE02_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n# 6. Bivariate Analysis\n\nFor analyses involving relationships between multiple variables, both **exploratory and confirmatory analysis** will be performed. Two approaches will be evaluated: using **ggstatsplot**, which integrates statistical testing and visualisation within a single function, and using **ggpubr**, which allows statistical test results to be added separately to ggplot visualisations. The functionality and suitability of these approaches will be compared before deciding whether to implement one or both methods in the final application.\n\n## 6.1 Categorical vs Numerical Variables\n\nThis will compare the values of a numeric variable across the categories of another variable.\n\nFor example, average transaction value can be compared across income brackets to observe whether higher-income customers tend to perform higher-value transactions. Visualisations such as raincloud plots, violin plots, or boxplots will be explored to illustrate the distribution of values across categories. Ridgeline plots are also quite useful when the categories are many, for e.g. location.\n\n### Testing the code for raincloud plot (EDA):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(df, aes(x = income_bracket,   #input$caty\n               y = avg_tx_value)) +  #input$numx\n     stat_halfeye(adjust = 0.5,\n               justification = -0.2,\n               .width = 0,\n               point_colour = NA) +\n  geom_boxplot(width = .20,\n               outlier.shape = NA) +\n  stat_dots(side = \"left\", \n            justification = 1.2, \n            binwidth = .5,\n            dotsize = 1.5) +\n  coord_flip()\n```\n\n::: {.cell-output-display}\n![](THE02_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n### Testing the code for CDA\n\n1.  Using ggpubr package\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggboxplot(df,\n          x = \"income_bracket\",\n          y = \"avg_tx_value\",\n          fill = \"income_bracket\") +\n  stat_compare_means(method = \"kruskal.test\") + #input$catnumtest\n  stat_summary(\n  fun.data = ~mean_cl_normal(.x, conf.int = 0.99),  #input$catnumlevel\n  geom = \"errorbar\",\n  width = 0.2)\n```\n\n::: {.cell-output-display}\n![](THE02_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n2.  Using ggstatsplot package\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggbetweenstats(            \n  data = df,\n  x = income_bracket,\n  y = avg_tx_value,\n  type = \"nonparametric\",  #input$catnumtest\n  conf.level = 0.99        #input$catnumlevel\n)\n```\n\n::: {.cell-output-display}\n![](THE02_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\nComparing the outputs of the two approaches, **ggstatsplot** provides richer statistical information directly within the visualisation. It displays the sample size for each group, the test statistic, p-value, and effect size, while also allowing the confidence interval level to be easily specified.\n\n### Testing the code for Ridgeline Plots (EDA):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(df,\n       aes(x = avg_tx_value, \n           y = location, \n           fill = factor(after_stat(quantile))\n           )) +\n  stat_density_ridges(\n    geom = \"density_ridges_gradient\",\n    calc_ecdf = TRUE, \n    quantiles = 4,\n    quantile_lines = TRUE) +\n  scale_fill_viridis_d(name = \"Quartiles\") +\n  theme_ridges()\n```\n\n::: {.cell-output-display}\n![](THE02_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n## 6.2 Numerical vs Numerical Variables\n\nWhen both variables are numeric, the objective is to examine whether a relationship exists between the two variables.\n\nFor example, **application login frequency** and **monthly transaction count** may be related if customers who interact with the application more frequently also perform more transactions.\n\nScatter plots will be used to visualise such relationships.\n\n### Testing the code for scatter plot (EDA):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(df,\n       aes(x = app_logins_frequency,\n           y = monthly_transaction_count)) +\n  geom_point(alpha = 0.6) +\n  geom_smooth()\n```\n\n::: {.cell-output-display}\n![](THE02_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n### Testing the code for CDA:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggscatterstats(\n  data = df,\n  x = app_logins_frequency,\n  y = monthly_transaction_count,\n  marginal = FALSE\n)\n```\n\n::: {.cell-output-display}\n![](THE02_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n## 6.3 Categorical vs Categorical Variables\n\nWhen both variables are categorical, the goal is to examine whether there is an association between the categories.\n\nFor example, the relationship between **income bracket** and **preferred transaction type** may reveal whether customers with different income levels prefer different transaction behaviours.\n\nBar charts and mosaic plots will be used to visualise such relationships.\n\n### Testing the code for bar chart (EDA):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(df,\n       aes(x = income_bracket,\n           fill = preferred_transaction_type)) +\n  geom_bar(position = \"fill\") +\n  labs(y = \"Proportion\")\n```\n\n::: {.cell-output-display}\n![](THE02_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\n### Testing the code for mosaic plot (EDA):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = df) +\n  geom_mosaic(\n    aes(x = product(income_bracket),\n        fill = preferred_transaction_type)\n  ) +\n  labs(\n    title = \"Relationship Between Income Bracket and Preferred Transaction Type\",\n    x = \"Income Bracket\",\n    y = \"Proportion\"\n  )\n```\n\n::: {.cell-output-display}\n![](THE02_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n### Testing the code for CDA:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggbarstats(\n  data = df,\n  x = income_bracket,\n  y = preferred_transaction_type,\n  conf.level = 0.99\n)\n```\n\n::: {.cell-output-display}\n![](THE02_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n# 7. UI Design for shiny app\n\n## Draft of proposed layout and features for Univariate Analysis EDA:\n\n![](/IMG_0236.jpg)\n\nFor the univariate analysis exploration, the user will first be able to select the broad category of variable from demographic, transactions, products, app usage and satisfaction. Then they will only be allowed to select the variable whose distribution they want to visualise, not the type of chart.\n\nThe naming convention used for the input Ids will be the first four letters of the type of variable from demographic, transactions, products, app usage and satisfaction. The PlotOutput will be named on the basis of the broad category the variable belongs to and the type of plot being returned (e.g. demoBox for demographic variable with a box plot)\n\n## Draft of proposed layout for Bivariate Analysis EDA and CDA combined:\n\n![](/IMG_0238.jpg)\n\nFor the bivariate and multivariate analysis, the user will be allowed to run step 1 (EDA) on its own, and step 2 (CDA) only after step 1 has run.\n\nWhen clicking on bivariate, the user will first be able to select the type of variables they want to analyse - whether 1 categorical and 1 numerical, or 2 numerical variables, or 2 categorical variables.\n\nFollowing that, the parameters exposed are as follows:\n\nVariables - Variable 1 and Variable 2\n\nStatistical Test Selection - Parametric, Non-parametric\n\nConfidence Interval - 90%, 95%, 99%\n\n## Shiny UI Components Used:\n\n| Parameter | UI Component | Purpose |\n|------------------------|------------------------|------------------------|\n| Variable selection | selectInput() | Allows users to select variables for analysis |\n| Statistical test type | selectInput() | Select the type of statistical test to be done |\n| Confidence level | selectInput() or sliderInput() | Adjust the confidence level used in test |\n| Run analysis | actionButton() | Runs the analysis |\n| Graph display | plotOuput() | Displays the visualisation |\n",
    "supporting": [
      "THE02_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/htmltools-fill-0.5.9/fill.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<link href=\"../site_libs/ggiraphjs-0.9.2/girafe.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/ggiraphjs-0.9.2/girafe.js\"></script>\n<script src=\"../site_libs/girafe-binding-0.9.3/girafe.js\"></script>\n<script src=\"../site_libs/plotly-binding-4.12.0/plotly.js\"></script>\n<script src=\"../site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"../site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"../site_libs/crosstalk-1.2.2/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/crosstalk-1.2.2/js/crosstalk.min.js\"></script>\n<link href=\"../site_libs/plotly-htmlwidgets-css-2.25.2/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/plotly-main-2.25.2/plotly-latest.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}